# INTRODUCTION {#sec:introduction}

## **THE GULLY MARINE PROTECTED AREA**

Submarine canyons are common geomorphic features of continental margins worldwide. Their complex topography influences a number of hydrodynamical processes, such as ocean currents, tides, and internal waves, which may have a profound effect on the structure, function, and diversity of their residing pelagic and benthic communities (@kenchington_2014b; @macisaac_2014; @fernandez-arcaya_2017]. Enhanced species diversity of canyon features has been linked to increased nutrient fluxes generated by upwelling [@freeland_topographically_1982].

The Gully canyon is the largest submarine canyon on the continental margin of eastern North America [@gordon_2002]. Located 40 km east of Sable Island, the Gully incises the Scotian Shelf between Sable Island Bank and Banquereau, is over 65 km long and 15 km wide, and reaches a depth of 2000 m at the shelf break. Since the 1990’s, the Gully has been an area of special conservation interest due to its abundance and diversity of benthic features, including cold-water corals and various commercial and non-commercial fish species, and for its diverse community of marine mammals. Fisheries and Oceans Canada (DFO) designated the area a whale sanctuary in 1994 in an effort to reduce ship collisions and noise disturbance for an endangered population of Northern Bottlenose whales that resides there [@dfo_2008]. In response to concerns over the impact of various anthropogenic activities, including offshore oil and gas exploration, shipping and commercial fishing activity (@vanderzwaag_2011) in the Gully and on its associated biodiversity, in 2004 DFO established the Gully as Atlantic Canada’s first Marine Protected Area (MPA) under Canada’s Oceans Act. [The Gully MPA](https://www.dfo-mpo.gc.ca/oceans/mpa-zpm/gully/index-eng.html) encompasses an area of 2364 km^2^, and is comprised of three different management zones that each have their own set of management measures and levels of protection.

## **ENVIRONMENTAL MONITORING OF THE GULLY**

In 1998, a comprehensive scientific review of the Gully’s environmental and ecosystem characteristics was published in support of MPA planning [@harrison_1998], and included the first synopsis of the Gully’s physical oceanographic properties (see @petrie_1998). Using data archived at the Bedford Institute of Oceanography, patterns in the Gully’s observed and modelled circulation, low-frequency current variability and cross-shelf exchange, internal tidal generation, and seasonal and inter-annual variability in hydrographic properties were examined. Some evidence pointing to localized retention of particles within the Gully was presented, which had long been theorized to drive enhanced primary productivity and biodiversity of the Gully [@harrison_1998]. However, the authors noted that the conclusions of the circulation models were based on relatively few observations, and that oceanographic data are lacking in the Gully, particularly in its deeper regions. In 2006 and 2007, a high spatial-resolution field program was later conducted in the Gully (see [@greenan_2014]; [@shan_2014a]; [@shan_2014b]), where both continuous (i.e., current-meter moorings deployed from April 2006 to August 2007) and discrete (i.e., CTD) observations were collected in order to better describe its mean circulation and evaluate evidence for enhanced mixing, flux, and other physical oceanographic properties that may differentiate the canyon from adjacent shelf and slope areas. These data have since been re-examined for the purpose of providing a comprehensive environmental background of the Gully to assist in the interpretation of catch data from midwater-trawl surveys of the nekton and micronekton at meso- and bathypelagic depths (see @kenchington_2014b).

In 2008, the Gully Marine Protected Area Management Plan (@dfo_2008; second edition released in 2017: @dfo_2017) was released, which outlines the conservation, management, and stewardship objectives for the MPA as well as key research and monitoring goals. The overarching conservation objective of the MPA is to “protect the health and integrity of the Gully ecosystem”, and is divided into three different sub-objectives:

1)	Protect the natural biodiversity of the Gully

2)	Protect the physical structure of the Gully and its physical and chemical properties

3)	Maintain the productivity of the Gully ecosystem

The Gully Marine Protected Area Management Plan also describes several, high priority conservation objectives, which were intended to be the focus of future monitoring efforts (@dfo_2010):

1)	Protecting cetaceans from impacts caused by human activities

2)	Protecting seafloor habitat and associated benthic communities from alteration caused by human activities

3)	Maintaining or restoring the quality of the water and sediments of the Gully

4)	Conserving other commercial and non-commercial living resources 
In order to address these conservation objectives, [@kenchington_2010] developed a recommendation for monitoring for the Gully that consisted of 47 indicators and advice on how to implement a cost-effective and efficient monitoring program that incorporated data collected by existing monitoring platforms. Of these 47 indicators, 8 were developed to monitor the physical, chemical, and biological state of the MPA:

1)	Temperature, salinity, oxygen concentration, alkalinity, pH, light levels, chlorophyll, pigments and nutrients in the water column within the MPA, including in close proximity to the seabed (Indicator 21)

2)	Temperature, salinity, oxygen concentration, light levels, chlorophyll, pigments and nutrients in waters flowing into and past the MPA, as measured on the Louisbourg Line, the Halifax Line and the Extended Halifax Line (Indicator 22)

3)	Physical (temperature, salinity, wind, sea-surface height) and biological (ocean colour) sea surface properties in the MPA and the surrounding region (Indicator 23) 

4)	Weather conditions at the Sable Island weather station and at the Banquereau and Laurentian Fan weather-buoy sites, including wind direction and speed, air pressure and sea-level air temperatures, plus for the buoy sites sea surface temperatures, wave height and dominant wave period	(Indicator 24)

5)	Three-dimensional distribution and movements of water masses within and around the MPA (Indicator 25)

6)	Phytoplankton production, community composition and the timing of the spring bloom in the MPA and the surrounding region (Indicator 26)

7)	Zooplankton biomass, community composition and the biomass of selected species within the MPA (Indicator 27)

8)	Acoustic scattering in the water column within the MPA (Indicator 28)	

Data on indicators 21, 22, 27, and aspects of indicator 26, are routinely collected during biannual monitoring surveys conducted by the [Atlantic Zone Monitoring Program](https://www.dfo-mpo.gc.ca/science/data-donnees/azmp-pmza/index-eng.html) (AZMP). Initiated in 1998, the AZMP was designed to build upon existing regional monitoring activities with the aim of detecting and tracking climate change and variability in the northwest Atlantic, evaluating changes in physical, chemical and biological ocean properties and predator-prey dynamics of marine resources, thereby enhancing Canada’s capacity to understand, describe, and forecast the state of the marine ecosystem [@harrison_2002]. AZMP’s sampling scheme in the Maritimes Region involves oceanographic sampling at several high-frequency (biweekly to monthly) fixed coastal stations and biannual sampling along fixed core sections (Cabot Strait Line, Louisbourg Line, Halifax Line, Browns Bank Line); the latter of which may also include opportunistic sampling at stations in the Laurentian Channel, Northeast Channel and Gulf of Maine in support of a number of ancillary research programs and initiatives. Oceanographic sampling includes the collection of CTD profiles and water samples for the determination of physical (T, S), chemical (nutrients, O2, pH, alkalinity) and biological (chlorophyll a concentration) variables and vertical ring net tows to determine zooplankton biomass and community composition. The same measurements are also made at random-stratified (by depth) locations during DFO’s multispecies groundfish trawl surveys.

At present, the AZMP has four fixed stations within the confines of the Gully MPA that are targeted for sample collection during its biannual surveys (see Figures 1 and 2). Station GULD_04, situated above the thalweg (Figure 2) of the canyon at approximately 1855 m depth, was first occupied and hydrographic data collected during the AZMP Hudson and Parizeau cruises of 1999 and 2000 (see Table 1), which were aimed at collecting acoustic backscatter data for the evaluation of seasonal changes in the abundance and community structure of mesozooplankton, macrozooplankton, and micronekton in the Gully and on western Scotian Shelf and Slope [@sameoto_2002]. Hydrographic data were first collected at GULD_03 in 2000, after the acoustic data and BIONESS tows collected in the northern shallow arms of the Gully revealed high euphausiid abundances at this location [@sameoto_2002]. Stations SG_23 and SG_28 on the eastern and western flanks of the Gully mouth, respectively, were later adopted from the high spatial-resolution CTD surveys conducted in the Gully in 2006 and 2007 [@greenan_2014]. As sampling at these stations initially served a purpose other than long-term environmental monitoring, their occupation on an annual basis was not consistent until after 2007.

## **GULLY DATA SYNTHESIS PROJECT**

Since the environmental setting of the Gully was first described and the recommended environmental monitoring program released, little has been done to assess changes in the physical, chemical, or biological state of the MPA, a key component in evaluating whether the MPA is meeting its conservation objectives. A critical first step towards forming a baseline for on-going future environmental monitoring is to compile, analyze, and interpret the existing data collected within the confines of the Gully MPA [@kenchington_2010], a task which, to date, has not yet been undertaken. In 2019, a joint project between DFO’s Maritimes Region Canadian Science Advisory Secretariat (CSAS) and the AZMP was initiated entitled “Synthesis of Gully MPA Oceanographic Monitoring Data”, with the overall goal compiling existing data collected on the physical, chemical, and biological conditions of the Gully MPA, and identifying patterns that may point to a change in the physical or chemical conditions, and/or productivity of the MPA. Three objectives and two deliverables of the project were outlined:

### _Objectives_

1.	Provide a synthesis of the physical, chemical, and biological data collected at the AZMP’s four fixed stations in the Gully MPA. 

2.	Identify any gaps or redundancies in the current monitoring protocols and provide recommendations on how to mitigate these gaps.

3.	Develop scripts, analytical products and a preliminary report that will form the basis of future routine environmental monitoring of the Gully MPA.

### _Deliverables_

1.	A technical report describing the AZMP’s sampling scheme and data collected at the program’s four fixed stations in the Gully MPA. The current sampling scheme, and temporal changes in the physical, chemical, and biological conditions at each station should be evaluated.

2.	A repository containing all of the data, scripts, analytical products and code for report generation that will serve as the template of future Gully MPA oceanographic reporting.

Here we present the first compilation of the physical, chemical, and biological data collected by the AZMP at the four fixed stations in the Gully MPA. CTD profile data collected from 1999 to 2018 were compiled, and average temperature, salinity, dissolved oxygen, and nutrient and chlorophyll a inventories were evaluated both within and among the four stations. In addition to the shipboard samples and data collected by the AZMP, sea surface temperature and chlorophyll a extracted from satellite-based imagery collected from 1998 to 2018 were also evaluated. While the datasets were deemed insufficient for climatological calculations for which to assess anomalies, changes in oceanographic conditions over the time period sampled were assessed, and significant trends identified.

The overall goal of the analyses presented in this report is to provide operational advice for effective monitoring of the Gully’s oceanographic properties by the AZMP. The discussion section is focused on identifying redundancies and gaps in existing AZMP monitoring protocols for the Gully MPA, including whether the placement and number of stations is adequate for detecting changes in oceanographic conditions within its confines. 

Additionally, we provide the first preliminary assessment of the oceanographic environmental monitoring indicators presented in @kenchington_2010. Aspects of Indicators 21, 22, 23, 26, and 27 are evaluated and discussed herein.

\clearpage
