# DATA AND METHODOLOGY {#sec:data}

## **PHYSICAL** {#sec:physical-data}

### _Data collection and compilation_

A data selection exercise was undertaken to extract all CTD casts conducted at or within the vicinity of the current nominal coordinates of the four monitoring stations in the Gully MPA. Extracting the data using spatial criteria was necessary as station names were often not consistently provided for CTD deployments conducted prior to 2013. Initially, all CTD profiles collected within 2.25 km (to account for vessel drift) of the nominal coordinates of each of the four AZMP fixed stations were queried and extracted from the Ocean Data and Information Section (ODIS) CTD Archive, a local, shared network drive used to house all CTD data collected by the AZMP. After this extraction revealed a low number results, all profiles assigned with the desired station name were queried and extracted from the archive, regardless of distance from the nominal station location. All profiles resulting from the above extractions were plotted using ArcMap GIS software (version 10.7.1) and their placement in relation to the nominal station coordinates and nearby topographic features (e.g. shallow banks) were evaluated. Some profiles conducted on the shallow bank within the immediate vicinity of GULD_03 were removed, as the hydrographic conditions were likely different from those occurring closer to the canyon thalweg where GULD_03 is located. A cluster of CTD casts located approximately 3 km to the northwest of GULD_03 was retained, as this location likely served as the former nominal location for station GULD_03.

The maximum depth of each profile was then evaluated against both the nominal station depth based on the General Bathymetric Chart of the Oceans (GEBCO) 2019 bathymetric data, and the total water depth based on ship’s sounding. Profiles with a maximum depth of 200 m or greater than the nominal station depth were not considered further. Profiles that were aborted at the surface were removed, as were profiles that reached water depths ≥200 m than the nominal station depth based on GEBCO. Four additional CTD profiles collected in March 2010 during a survey to quantify the mesopelagic communities of the Gully were also excluded from all subsequent analyses. 

This data reduction exercise resulted in a total of 89 profiles collected across all four monitoring stations between 1999 and 2018 (see Table \@ref(tab:table1) and Figure \@ref(fig:figure2)). The majority of the profiles were collected during AZMP’s biannual surveys, while others were collected during the targeted oceanographic survey of @greenan_2014. While the four AZMP fixed stations have been occasionally sampled during DFO’s multispecies research vessel trawl survey, those profiles were not considered to meet the data selection criteria described above, and are consequently not included in this report.

A similar data exercise was undertaken to extract the CTD profile data collected from AZMP core stations on the Louisbourg and Halifax Lines, in order to capture waters flowing into (Louisbourg Line, upstream of the Gully) and past the MPA (Halifax Line, downstream of the Gully), and to compare their conditions with those in the Gully MPA. CTD profiles collected during the AZMP biannual surveys conducted between 2000 to 2018 collected at the Louisbourg Line station LL_07 (nominal depth approximately 760 m) and Halifax Line station HL_06 (nominal depth approximately 1100 m) (Figure \@ref(fig:figure3)). These stations were chosen as they are situated close to the shelf break, and are influenced by the southwestward along-slope current originating from the offshore branch of the Labrador Current [@dever_2016].

Data collection procedures for all CTD profiles analyzed in this report were considered to follow AZMP standard collection protocols [see @mitchell_2002]. In all cases, full-length profiles of water column properties were collected using a Sea-Bird 911 CTD-rosette equipped with dual temperature, conductivity, and dissolved oxygen sensors, fluorescence (chlorophyll) and coloured dissolved organic matter (CDOM) sensors, and a single pH sensor (rated to 1200 m depth). The optical properties of seawater (attenuation coefficient and euphotic depth) are derived from _in situ_ light extinction measurements collected using a single, rosette-mounted photosynthetically active radiation (PAR) sensor. Only the temperature, salinity, and dissolved oxygen sensor data are analyzed and presented as part of this report. PAR and fluorescence are generally available for the entire time period the Gully has been sampled by the AZMP. Data on pH were only available from 2008 onward, and the depth limitation of this sensor meant that data on pH were not collected at station GULD_04. Thus, pH was also not evaluated in this report.

### _Analysis_

Mean vertical structure in temperature, salinity, and dissolved oxygen concentration from the CTD profiles was evaluated at each station for the spring and fall seasons only. The 89 selected profiles (Table \@ref(tab:table1)) were filtered further to include only those profiles collected in April (spring) and September-October (fall), resulting in 82 profiles for the seasonal analyses. Those profiles collected outside these months/seasons (7 profiles – November and December; see Table \@ref(tab:table1)) were not considered further in this report. Table \@ref(tab:table2) shows the number of CTD profiles contributing to the seasonally-averaged datasets computed for each station. 

Temperature, salinity, and dissolved oxygen data collected in the top 10 m of each profile were excluded from the vertically-averaged profiles, due to the high mixing that occurs at the surface and potentially erroneous data values. Means were computed using the R statistical software suite (version 4.0.2) by averaging the values in 1 dbar pressure bins across profiles, and are presented with $\pm$ 95% confidence intervals. Vertical profiles were displayed using the R package ‘ggplot2’ [@wickham_2016].

Starting in 2013, the program’s collected oxygen sensor data are routinely calibrated by ODIS using dissolved oxygen measurements derived using the Winkler titration method. Prior to 2013, calibrations of dissolved oxygen data were based on the sensor manufacturer’s calibration values. As data calibrated using Winkler titration measurements are considered more reliable, only those CTD profiles collected in 2013 onward were included in the calculation of seasonally-averaged dissolved oxygen profiles.

Using the ‘plotTS’ function of R package ‘oce’ [@kelley_2020], seasonal temperature-salinity (T-S) plots were computed for each of the four stations. Profiles were colour-coded according to the year in which they were collected, and isopycnal (density) curves were added using the ‘drawIsopycnals’ function of ‘oce’, in order to deduce any changes in water mass structure at each station over time.

Among-station variability in spring and fall temperature, salinity, and dissolved oxygen concentration in the Gully was evaluated by superimposing the vertically-averaged profiles of temperature, salinity, and dissolved oxygen calculated at each station and season, and qualitatively comparing their properties across similar depth intervals. Mean vertical structure in seasonal temperature, salinity, and dissolved oxygen in areas upstream (LL_07) and downstream (HL_06) of the MPA were also evaluated and compared to the water column properties of the four Gully stations.

Temporal changes in spring and fall temperature, salinity, and dissolved oxygen concentration were evaluated across the time series available for each station (see Table \@ref(tab:table2)). Mean temperature, salinity, and dissolved oxygen from each profile were averaged within the following depth intervals: 0 - 50 m, 50 - 100 m, 100 - 400 m, 400 - 750 m, and 750 m to near-bottom, and mean values were compared between years and stations across the time series. These intervals were chosen in order to highlight the temporal changes in the different water layers that were depicted in the vertically-averaged temperature, salinity and dissolved oxygen profiles. The lower bounds of the 750 to near-bottom interval varied between seasons within stations depending on the maximum depth attained by the CTD package. The 400 - 750 m interval extends to the seabed on GULD_03. Linear regression techniques were used to evaluate the patterns and significance of the relationships between year and average temperature, salinity, and dissolved oxygen calculated at each depth interval. Pearson correlation coefficients were shown for statistically-significant trends in temperature.

## **CHEMICAL** {#sec:chemical-data}

### _Data collection and compilation_

The nominal depths of discrete water samples collected using Niskin bottles at each of the four AZMP fixed stations in the Gully are shown in Table \@ref(tab:table3). Standard AZMP measurements include nutrient analyses (nitrate, reported as nitrate+nitrite, nitrite, phosphate, silicate, and ammonia), chlorophyll _a_ concentration measured using Turner Fluorometry, salinity, and dissolved oxygen concentration. At the time of this report, salinity and dissolved oxygen samples are collected at 10 m, 250 m, and near-bottom at all stations for the purpose of calibrating the CTD sensor data. Nutrients and chlorophyll samples are collected in duplicate at all nominal depths sampled. 

Ancillary data collection includes samples for total inorganic carbon (TIC), total alkalinity (TA), and the partial pressure of carbon dioxide (pCO\textsubscript{2}) measured for the purpose of evaluating the carbonate system and ocean acidification. Phytoplankton samples on filters are collected for detailed pigment analysis via high performance liquid chromatography (HPLC) analysis and light absorption spectra (ABS), which are used in the interpretation and calibration of ocean colour measurements made by satellite remote-sensing. Particulate organic carbon (POC) samples are collected for the purpose of tracking changes in POC to chlorophyll ratios in an effort to see how much POC is associated with phytoplankton, which has a relatively stable POC to chlorophyll ratio, versus non-phytoplankton particles such as detritus and/or microzooplankon. Finally, samples are collected for estimating the abundance of microbial plankton (phytoplankton, bacterioplankton, virioplankton) using flow cytometry methods. Nominal depths of ancillary measurements may vary from year to year depending on mission objectives, although only surface samples are generally collected for POC, HPLC and ABS analysis. 

The concentrations of the three primary dissolved inorganic nutrients (nitrate, here measured as nitrate+nitrite, phosphate, and silicate) collected from the four Gully stations were queried and extracted from DFO’s [BioChem database](https://www.dfo-mpo.gc.ca/science/data-donnees/biochem/index-eng.html), an open-access data repository that contains both discrete (e.g. nutrients, pH, oxygen) and depth-integrated (e.g. plankton) samples collected and maintained by DFO. Nutrient and chlorophyll _a_ data from bottle samples collected on each of the 82 CTD profiles used in the seasonal analyses presented in this report were targeted for extraction from BioChem. 

### _Analysis_

Mean vertical structure in spring and fall nitrate, phosphate, and silicate concentration was evaluated at each station by calculating the average nutrient concentration ($\mu$M) across bottle samples collected at each of the standard nominal depths sampled (Table \@ref(tab:table3)): near-surface (0 - 5 m), 10 m, 20 m, 30 m, 40 m, 50 m, 60 m, 80 m, 100 m, 250 m, 500 m (when applicable), 750 m (when applicable), 1500 m (when applicable), and near-bottom. Data were extracted at each nominal depth +/- 5 m (e.g., 5 - 15 m for the 10 m depth interval) to account for variability in the depth of the CTD package when bottles were closed. The spring and fall near-bottom layer for each station was defined as follows: >400 m for GULD_03, > 1900 m for GULD_04, > 940 m for SG_23, and >793 m for SG_28. The lower depth limit of samples collected in the near-bottom intervals varied between CTD casts made at each station. The average depth of each near-bottom interval was 456.36 m $\pm$ 40.44 m (mean $\pm$ SD) and 478.08 m $\pm$ 50.17 m for spring and fall data, respectively at GULD_03; 2155.51 m $\pm$ 79.51 m and 2123.51 m $\pm$ 80.32 m for spring and fall at GULD_04; 1130.71 m $\pm$ 126.78 m and 1214.92 m $\pm$ 144.89 m for spring and fall at SG_23; and 886.35 m $\pm$ 71.16 m and 860.09 m $\pm$ 41.51 m for spring and fall at SG_28.

Integrated nutrient inventories were calculated over 3 different depth intervals (0 - 50 m, 50 - 250 m, 250 - 400 m using the trapezoidal method for numerical integration [see @casault_2020] for a similar application) and temporal changes at each station and between seasons were examined. The depth intervals used here were different from those used to evaluate temporal changes in the physical oceanographic parameters (temperature, salinity, and dissolved oxygen). As sensor data are available at 1 m depth intervals, profiles can be analyzed at a relatively high resolution. In contrast, nutrient concentrations are only measured at the depths at which bottle samples are collected. Thus, for the 100 - 400 m and 400 - 750 m intervals applied to the physical data, nutrient concentrations would be extrapolated from bottle samples collected at 250 m (100 - 400 m), and at 500 and 750 m (400 - 750 m) (see Table \@ref(tab:table3)). Additional bottle samples would provide better resolution of the water column and allow for more congruent analyses between the  hydrographical and chemical parameters in the future. Linear regression techniques were used to evaluate the direction and strength of the relationship between nutrient concentrations and year over the time series at each station and season.

Mean vertical structure in chlorophyll _a_ concentration measured by Turner Fluorometry was evaluated at each station from samples collected at the near-surface (0 - 5 m), 10 m, 20 m, 30 m, 40 m, 50 m, 60 m, 80 m, 100 m nominal depths. Chlorophyll _a_ concentrations integrated over the 0 - 100 m depth interval were calculated using trapezoidal numerical integration and patterns were evaluated across seasons and stations. 

## **BIOLOGICAL**  {#sec:biological-data}

### _Data collection and compilation_

Vertical ring net tows are routinely conducted at each of the four monitoring stations in the Gully using a $\sfrac{3}{4}$ m diameter ring net with a 202 $\mu$m mesh, and towed from near-bottom to surface at approximately 1 m s\textsuperscript{-1} to a maximum of 1000 m. Samples are preserved in buffered formalin and split into two equal portions before further analysis. One half is sieved on a 1 cm sieve and the large and small fractions are weighed separately to give size fractionate bulk wet weight biomass. The other half is used for taxonomic analysis, and processed according to the standard AZMP protocols outlined in @mitchell_2002. All zooplankton tows conducted within 2 km of each of the four stations were extracted from BioChem for the evaluation of zooplankton composition, diversity, abundance, and wet and dry weight biomass. This resulted in 121 tows collected from 1999 to 2018 for analysis (see Table \@ref(tab:table4)).

Zooplankton biomass and abundance data collected at the four Gully stations were compared with measurements at core AZMP stations near the shelf break both upstream (LL_07) and downstream (HL_06) of the Gully (see Figure \@ref(fig:figure4)) over approximately the same time period in order to ascertain whether the Gully supports a different community composition, and/or higher abundances of zooplankton compared to the nearby slope water areas. Zooplankton sampling at station GULD_03 began in 2005 (fall), while sampling at the stations across the Gully mouth began later (2007). A total of 45 tows were made across all four Gully stations. Zooplankton sampling at HL_06 and LL_07 started in 1999, with 76 tows made between 1999 and 2018. 

Tows from all stations were delimited according to season, where spring is defined as April to June and fall is September to December. The slightly different seasonal delimitations used here compared to the physical and chemical data analyses (spring = April, fall = September/October) was necessary in order to capture the peaks in the phytoplankton bloom in each season, and the succession of zooplankton community composition that occurs as a result of these bloom dynamics. All tows collected in the spring from the Gully stations were from the month of April (Table \@ref(tab:table4)), while tows from HL_06 and LL_07 were collected from April to June, and April to May, respectively. Tows collected from the Gully stations and LL_07 in the fall were from September to December, while tows from HL_06 were September to November.

For each station, wet weight biomass concentrations were calculated for the large and small size fractions for every year and season sampled. Multi-year average zooplankton abundances were calculated for all samples collected at LL_07 and HL_06 in spring and fall between 1999 and 2018. For the Gully, abundances were averaged over samples collected at one station within the Gully (GULD_03) between 2005 and 2018, and over samples collected at the three monitoring stations across the Gully mouth (SG_23, GULD_04, SG_28) between 2007 and 2018.

### _Analysis_

Preliminary analyses of the zooplankton samples indicated that copepods comprised the majority of the zooplankton. Here, abundance data are presented only for the 16 copepod taxonomic groups (taxa) that comprised the 10 most abundant taxa at all four sites in spring and fall. Some taxa are individual species (_Calanus finmarchicus_, _Calanus hyperboreus_, _Mecynocera clausi_, and _Temora longicornis_) and some are the sum of all species/categories within a genus (_Centropages_, _Clausocalanus_, _Microcalanus_, _Oncaea_, _Paracalanus_, _Pleuromamma_, _Pseudocalanus_, and _Scolecithrocella_). Young stage _Metridia_ and _Oithona_, which are not identified to species level, were assigned to the individual species (_Metridia longa_ and _Metridia lucens_ or _Oithona atlantica_ and _Oithona similis_) according to the relative abundances of the late stage individuals, which were identified to species level. Other copepod categories were grouped in similar ways before the determination of the ten most abundant taxa at each site.

## **REMOTE SENSING DATA FOR EVALUATION OF SURFACE TEMPERATURE, PHYTOPLANKTON CONCENTRATION & SPRING BLOOM METRICS**

### _Data collection and compilation_

Although limited to the ocean’s surface, remote sensing data provides greater temporal and spatial coverage than the discrete data collected by the AZMP, and are useful for comparing oceanographic features at the surface of the Gully with those of nearby locations. In this report, satellite observations of sea surface temperature (SST) and sea surface chlorophyll (SSC) for areas upstream (Slope Water LL, ‘SW LL’) and downstream (Slope Water HL, ‘SW HL’) of the Gully were extracted for the 1998 - 2018 time period and compared to those made for the Gully MPA (‘GMPA’). Figure \@ref(fig:figure4) shows a depiction of the spatial configuration of the SW LL, SW HL, and GMPA polygons used for the extraction of satellite observations. 

### _Analysis_

SST and SSC average seasonal cycles, spring bloom metrics, and trends over time were evaluated between the 3 polygon locations. SeaWiFS data from January 1998 to December 2007, MODIS data from January 2008 to December 2011 and VIIRS data from January 2012 to December 2016 were combined to construct composite time series of SSC in the selected polygons described above. This follows the protocol used in the annual AZMP reports [@casault_2020]. Additionally, spring bloom metrics were determined from weekly satellite measurements by fitting a shifted Gaussian function of time model [@zhai_2011]. Four metrics were computed: bloom initiation date (date when SSC reaches 20% of its peak value), bloom amplitude (peak SSC value minus the background chlorophyll concentration), bloom duration (date when bloom returns to 20% bloom peak minus bloom initiation date), and bloom magnitude (the integral under the Gaussian curve).

## **REPRODUCIBLE REPORTING & CODE REPOSITORY**

Over the past several years, DFO has aimed to apply tools developed in open-source analytical programs, such as R, that allow for the creation of automated and reproducible reports [see @gomez_2020 for overview]. Such tools are particularly useful in applications involving routine reporting or monitoring, as they ensure consistent and automated formatting within and between publications, enhance data review and transparency, and help facilitate discussions with both internal and external clients and members of the public [@anderson_2019].

Given that this report represents the first compilation and preliminary analysis of the oceanographic conditions of the Gully, a primary objective was to archive the code used to generate the report to allow for consistent reporting in the future.

R package ‘csasdown’ [@anderson_2020] was used as the primary mechanism to generate this report. This package was developed by members of DFO’s Pacific Region to facilitate the creation of CSAS documents in PDF or Word format using the previously-developed  ‘rmarkdown’ and ‘bookdown’ packages, and has recently been applied to generate a CSAS document presenting a synthesis of available fishery and biological data and basic model fits for 109 groundfish species in the Pacific [@anderson_2019].

RStudio, an integrated development environment (IDE) for R, was used to assemble, manipulate, and execute the R code, and produce the analytical products presented in this report. The R code used to create the PDF version of this report is archived in [GitHub: https://github.com/AtlanticR/reproducible-gully-report](https://github.com/AtlanticR/reproducible-gully-report).

The analyses presented here are a compilation of both R and excel outputs. All of the tables and more than half of the figures are dynamically generated. While this publication encapsulates the first step towards reproducible reporting on the oceanographic conditions of the Gully MPA, future iterations should strive towards fully automating the analyses presented herein.

\clearpage
