# RESULTS {#sec:results}

## **HYDROGRAPHIC DATA ANALYSES** {#sec:hydrographic-analyses}

### _Seasonal depth-dependent patterns in temperature, salinity, and dissolved oxygen in the Gully and surrounds_

The mean vertical structure of temperature, salinity, and dissolved oxygen concentration in the spring (Figs. 5, 6, 7; top panel) exhibited a 3-layer structure, with a relatively cooler, fresher, and more oxygen-rich near-surface layer (0 - 100 m) that overlaid a warmer, more saline and oxygen-poor intermediate (approximately 100 to 300 m) layer. As depth increased beyond 400 m, water layers across all stations were cooler and fresher than those immediately above. The vertical structure of temperature in the fall was characteristically different than in the spring at every station (Figure 5; bottom panel). Near-surface mixed layers were shallower than in spring, and overlaid colder layers (cold intermediate layer, CIL) produced by vertical mixing during the previous winter in areas further upstream. Below these layers, temperatures first increased and then decreased with increasing depth. Temperatures in the 100 - 400 m and 400 - 750 m layers were similar in spring and fall for a given year and station. 

The high seasonal variability observed in temperature was not as prominent in salinity (Figure 6) or dissolved oxygen (Figure 7). Maximum dissolved oxygen concentration occurred in near-surface waters (0 - 50 m) in the spring (April), which generally corresponds to the timing of the spring bloom period, when photosynthetically-active phytoplankton would have been at their highest concentration. Maximum fall oxygen concentrations occurred between 50 and 100 m. Lower oxygen concentrations in near-surface layers in fall may have resulted from higher winds and increased exchange across the air/water interface compared to spring, which would result in a greater release of oxygen in near-surface waters to the atmosphere. 

Figure 8 shows a comparison between vertically-averaged temperature, salinity, and dissolved oxygen profiles at each of the four monitoring stations in the spring and fall. Waters near the head of the canyon at station GULD_03 were, on average, colder, fresher, and more oxygen-rich at all depths in both the spring and fall compared to the three stations situated across the Gully mouth. At similar depths, water properties were similar across the three Gully mouth stations (Figure 8), although station SG_28 was slightly warmer and more saline than SG_23 and GULD_04 below 100 m in the fall, while SG_23 was slightly warmer than the other two stations in the spring.

The seasonal T-S diagrams (Figure 9) showed that waters were consistently situated between the same density contours (26 - 28 kg m-3) in the spring at each of the four stations. However, in the fall, strong inter-annual variability in T-S properties was observed in the top 100 m at each of the three Gully mouth stations, but not near the Gully head (GULD_03). No clear temporal trends in T-S properties were observed over the time period sampled at each station. However, profiles collected in the early 2000’s in spring at GULD_03 appeared cooler than those collected in the late 2010’s at the same station. Station SG_28 showed anomalous T-S properties on the spring profile collected in 2018, where temperatures exceeded 10ºC over a range of salinity. This phenomenon was not observed in the data collected in the same year at the 3 other stations.  

Figures 10 through 12 depict temporal changes in seasonal temperature, salinity, and dissolved oxygen averaged across 5 vertical depth intervals (0 - 50 m, 50 - 100 m, 100 - 400 m, 400 - 750 m, and 750 - near-bottom) over the time series at each station. The 3-layer vertical structure in spring temperature identified in the vertically-averaged CTD profiles (Figure 5) was evident in Figure 10, with cooler near-surface layers (mean $\pm$ SD: 0 - 50 m: 4.02 $\pm$ 2.10⁰C; 50 - 100 m: 6.32 $\pm$ 3.18⁰C), warmer intermediate layers (100 - 400 m: 7.67 $\pm$ 1.46⁰C), and cooler deeper layers (400 - 70 m: 5.18 $\pm$ 0.63⁰C; 750 m - near-bottom: 4.63 $\pm$ 0.30⁰C) across all stations. At GULD_03, the depth of the cooler near-surface layer extended to 100 m, but was shallower (0 - 50 m) at the stations across the Gully mouth (SG_28, GULD_04, and SG_23). 

Increasing, statistically-significant trends in temperatures measured at sub-surface (50 - 100 m) and intermediate depths (100 - 400 m, 400 - 750 m) were evident at some stations (Figure 10 and Table \@ref(tab:table5)) in both spring and fall. Increasing trends were more prominent in spring than fall, and were strongest in the 100 - 400 m layer in spring (Table \@ref(tab:table5)). Temperatures in near-surface (0 - 50 m) layers were highly variable across years at all stations, but a statistically-significant increasing trend in spring temperature emerged at station SG_28 (Table \@ref(tab:table5)). The near-bottom layer at GULD_03, which ranged from >400 to approximately 589 m (depending on the ship’s position in this area which has steep bathymetry) also showed a slightly increasing and statistically significant trend in spring temperature over the 2000 to 2018 time period (Figure 9 and Table \@ref(tab:table5)), likely due to the shallower depth of this station. 

In fall (September-October), near-surface waters in the 0 - 50 m range were considerably warmer than in spring at all stations (mean $\pm$ SD: 12.18 $\pm$ 2.08⁰C), and reached a maximum of 17.19⁰C on station SG_28 in 2013. The 50 - 100 m layer was, on average, 5.41 $\pm$ 3.20⁰C across all stations in the Gully. The warm and saline intermediate layer (100 - 400 m: 8.15 $\pm$ 1.64⁰C) observed in the spring was also a prominent feature at all stations in fall. Average temperatures in the deeper layers (400 - 750 m: 5.28 $\pm$ 0.43⁰C; 750 m to near-bottom: 4.28 $\pm$ 0.29⁰C) were similar to those of spring and showed less variability compared to the shallower layers above. In 2013, there was a positive spike in fall temperatures in the upper layers at the Gully mouth stations (SG_28, GULD_04, and SG_23), but not at GULD_03. While statistically significant, increasing trends in fall temperatures were observed at some depth intervals (Table \@ref(tab:table5)), these may be due to the successively earlier date of the fall survey, which shifted from October in the early 2000’s to September (warmer) after 2012 (see Table \@ref(tab:table1)). Thus, any temporal trends in fall temperature may be confounded by sample date and should be interpreted with caution.

In contrast to temperature, patterns in salinity (Figure 11) and dissolved oxygen (Figure 12) were much more comparable between spring and fall, with fresher, more oxygen-rich near-surface layers (0  - 50 m and 50 - 100 m) and more saline, oxygen-depleted deeper layers at all stations and seasons. A dramatic, positive increase in salinity was observed between 0 and 100 m at the Gully mouth stations in the fall of 2013, consistent with increased temperatures (Figures 9 and 10). Dissolved oxygen was lowest in the intermediate (100 - 400 m) layer in that year, consistent with the properties of Warm Slope Water (WSW; Petrie and Yeats 2000). While temperature and salinity decreased from 2017 onward at GULD_03, dissolved oxygen concentration increased, suggesting a larger-than-average transport of cold, fresh, and oxygen-rich waters from the Gulf of St. Lawrence during those years (Petrie and Drinkwater 1993; Dever et al. 2016).

Figure 13 shows a comparison between the vertically-averaged temperature, salinity, and dissolved oxygen profiles to 1000 m at the four Gully stations and stations upstream (LL_07) and downstream (HL_06) of the Gully. The average temperature and salinity profiles at upstream station LL_07 were comparable to those of Gully head station GULD_03 in both spring and fall, while dissolved oxygen concentration was higher at GULD_03 than LL_07 in both seasons. In contrast, station HL_06 was typically warmer, saltier, and more oxygen-poor compared to all other stations. This pattern was more prominent in the fall than in spring.

### _Satellite observations of sea surface temperature and comparison with in situ measurements_

Average sea surface temperatures (SSTs) in the three satellite polygons were lowest in February-March and highest in August (Figure 14). SSTs were generally highest off the central Scotian Shelf in the SW HL area and more variable there than elsewhere, especially between August and April.  Annual average SSTs were well correlated among areas (p < 0.001). There were significant upward trends in the SW HL and SW LL areas over the 1998 to 2018 period, but not in the GMPA (Figure 15). The upward trends in SW HL and SW LL were consistent with in situ observations over the reduced sampling periods at the three Gully mouth stations (SG_23, GULD_04, SG_28), but not with those at GULD_03 (Figure 10). Average spring (Apr-Jun) and fall (Sep-Dec) SSTs were also well correlated among areas (p < 0.001), but none showed significant temporal trends.

Sea surface temperatures for the SW HL and SW LL areas for the appropriate months and years were well correlated with near-surface water temperatures measured in situ at HL_06 and LL_07 by the AZMP and other sampling missions in spring and fall (Figure 16). For the Gully MPA, in situ temperatures and SSTs were well correlated in fall, but not in spring. This could be due to the in situ measurements being taken at GULD_03, a station well within the Gully canyon proper, in contrast to the satellite GMPA, which includes some of the adjacent slope water where temperatures can be influenced by intrusions of warmer offshore water. In fall, near surface temperatures are more influenced by cooling from summer temperatures, caused by decreasing air temperatures and vertical mixing. Thus, SSTs and 5 m temperatures in spring in the SW HL and SW LL areas were quite variable within the month of April, while in fall they were less variable within months, but decreased markedly in both areas between September and December.

Although SSTs in the GMPA did not show significant trends in spring over the 1998 - 2018 period, in situ 5 m and 0 - 200 m average April temperatures showed significant positive trends for the 1999 - 2018 period at LL_07, and 0 - 200 m temperatures at GULD_03 showed a significant positive trend in at GULD_03 for years sampled between 2007 and 2018. 


## **CHEMICAL ANALYSES** {#sec:chemical-analyses}

### _Seasonal depth-dependent patterns in nutrient concentrations in the Gully_

All 3 inorganic nutrients showed similar relationships with depth between seasons (Figure 17), and between stations at comparable depths. In both spring and fall, nitrate and phosphate concentrations peaked at 250 m depth, and between 250 and 500 m for silicate. The average spring nitrate concentration across bottles collected within the top 250 m was lowest at GULD_03 (5.43 $\mu$M) compared to the three Gully mouth stations (9.48, 8.51, and 6.77 $\mu$M at GULD_04, SG_23, SG_28, respectively). However, fall nitrate concentration was highest at stations GULD_04 (5.30 $\mu$M) and GULD_03 (5.08 $\mu$M), with lower but comparable mean values at SG_23 (4.87 $\mu$M) and SG_28 (4.88 $\mu$M). GULD_03 and SG_28 showed slight increases in near-bottom nitrate, phosphate, and silicate concentrations in the spring compared to the overlying layers.

No trends seasonal trends in numerically-integrated nutrient concentrations were observed at each of the four Gully stations (Figures 18 through 21). Inter-annual variability in nutrient concentrations was highest between 0 - 50 m at all stations, where phytoplankton utilization and vertical mixing drive changes throughout the year. At stations GULD_03, SG_28, and GULD_04, spring and fall nitrate showed slightly increasing, statistically-significant trends in the 250 - 400 m depth interval. No patterns were observed between average nutrient concentrations observed in the Gully and those upstream or downstream of the canyon (Figure 22).

### _Seasonal depth-dependent patterns in chlorophyll a concentrations in the Gully_

Mean vertical profiles in spring and fall chlorophyll a concentrations are shown in Figure 23. Spring chlorophyll a concentrations varied between stations in the Gully, with GULD_03 featuring the highest average chlorophyll a over the 0 - 100 m depth interval in spring (3.93 $\mu$g L-1), SG_23 the lowest (1.05 $\mu$g L-1), and SG_28 and GULD_04 showing intermediate values (2.15 and 2.58 $\mu$g L-1, respectively). Spring chlorophyll a concentrations varied considerably among years (indicated by the high standard deviation in the means calculated across years at each nominal depth) at stations GULD_03, SG_28, and GULD_04, but not at station SG_23. Some of this variability may be due to differences in the timing of sampling versus the timing of the spring bloom, although this was not evaluated.

Chlorophyll a concentrations in the fall were generally low across the 0 - 100 m depth interval at all four stations (averages < 0.50 $\mu$g L-1). Sub-surface peaks were featured at all stations, albeit with low average peak concentrations (< 1.5 $\mu$g L-1; Figure 23).

Figure 24 shows the temporal changes in chlorophyll a concentrations integrated across the 0 - 100 m depth interval. Spring chlorophyll a concentrations varied considerably between years at GULD_03, SG_28, and GULD_04, but were relatively consistent at station SG_23 located on the western side of the Gully mouth. Fall chlorophyll a concentrations were relatively consistent across the time series at all four stations.

## **BIOLOGICAL ANALYSES** {#sec:biological-analyses}

### _Phytoplankton seasonal cycles and annual trends from satellite and in situ observations_

Average seasonal cycles of sea surface chlorophyll (SSC) concentration in the three satellite areas show patterns expected for temperate regions (Martinez et al. 2011; see Figure 25). Maximum SSC concentrations were observed during the spring bloom, which occurs when the water column stabilizes after intense winter vertical mixing. Water column stability (i.e. stratification) can be caused by the introduction of less saline waters into the near surface layers (e.g. via melting of sea ice, either locally or upstream) or by local surface warming, with thermal expansion causing the near surface waters to become less dense. These processes allow the phytoplankton to remain in the well-illuminated near surface layers, which have been supplied with nutrients required for phytoplankton growth by that same winter vertical mixing.

The average timing of the peaks in SSC concentrations were in late March in the SW HL area, in early April in the GMPA and in late April in the SW LL area. Following these peaks SSC concentrations dropped to their lowest values over the summer, rising slowly in fall, with secondary peaks occurring in November. Annual average SSC concentrations were significantly correlated among sites (p < 0.05, data not shown), but there were no significant trends over the 1998 - 2018 period (Figure 26).

SSC values were highly variable during the spring bloom, due to inter-annual variations in both the timing, duration and intensity of the spring bloom peak as manifested by the bloom metrics (Figure 27). Thus, while average bloom initiation dates and durations were indistinguishable among regions (Day of Year (DoY) ranges: 76 - 81 and 35 - 40 days, respectively), actual start dates and durations were much more variable (Ranges DoY 36 - 119 and 10 - 119 days over all areas, respectively). The average bloom magnitude was statistically slightly higher for the GMPA (45.4 mg m-3 d) than for the SW HL area (30.1 mg m-3 d), but neither of these was different from that for the SW LL area (41.0 mg m-3 d) and actual values over all regions varied between 9.7 and 104.7 mg m-3 d.  Finally, while average bloom amplitudes were also indistinguishable among regions (Range 1.43 - 2.20 mg m-3), actual values ranged between 0.6 and 6.3 mg m-3.

There were significant correlations between one or two pairs of bloom metrics at all sites, but they were inconsistent (Table \@ref(tab:table6)). Thus, earlier blooms lasted longer in the SW LL area and the GMPA, but not in the SW HL area. Furthermore, blooms that lasted longer had higher magnitudes in the SW LL and SW HL areas, but not in the GMPA, and bloom magnitudes were higher when SSTs were lower during the pre-bloom winter and spring bloom (January to April) period in the SW LL and SW HL areas. Spring SSTs trended upward over the 1998 - 2018 period in the GMPA and in the SW HL area, and in the latter area this was associated with an increasing trend in bloom start date.

Log-transformed phytoplankton chlorophyll a concentrations determined from water samples collected in the 0 - 10 m depth range at stations within the three satellite areas were well correlated with log transformed remotely-sensed SSC concentrations from the same months/years (Figure 28). Pearson correlation coefficients were higher for the GMPA and SW LL areas separately than for the entire dataset, while those for SW HL were lower. Additionally, in situ concentrations were generally lower than remotely-sensed SSC values at low chlorophyll concentrations, and higher at high chlorophyll concentrations. Such patterns are common for these types of comparisons, and are generally explained in terms of the differences in the spatial and temporal scales of the satellite measurements, and the phytoplankton species composition (Stuart et al. 1998, 2000; Sathyendranath et al. 2001; Bricaud et al. 2004). Thus, phytoplankton blooms are localized and short-lived, whereas remotely-sensed measurements are averaged over large areas and here, over approximately 30 day periods, leading to underestimation. In addition, at high chlorophyll concentrations phytoplankton communities are often dominated by large cells (e.g. diatoms), within which absorption of light relative to the concentration of chlorophyll is reduced due to intra-cellular self-shading (the “packaging effect”), again leading to underestimation. Finally, different phytoplankton species have different accessory pigments and inherently different light absorption characteristics, which can also influence the signal captured by remote sensing as well as the in situ measurements of chlorophyll concentration made using Turner Fluorometry. The lower R2 value for the SW HL area may thus indicate a higher diversity of phytoplankton species/types there, than in the GMPA and SW LL areas.

### _Distribution and time series of seasonal zooplankton biomass_

The biomass of small zooplankton (<1 cm) was generally higher than, or similar to, that of large zooplankton (>1 cm) in spring (Figure 29), except in 2002 and 2014 at HL_06 and in 2014 at LL_07, when the biomass of large zooplankton was unusually high. In 2002 the high biomass at HL_06 was due to the presence of salps , while in the other two instances it was associated with large decapods (e.g., Acanthephyra pelagica at HL_06,  and Pandalus borealis and Gennadas valens at LL_07). There were no significant trends in biomass over time for either size fraction at the two stations with the longest time series upstream and downstream of the Gully, LL_07 and HL_06, respectively. At SG_23 there appeared to be a downward trend in both size fractions over the four sampled years, but a comparison with the other stations suggests that these trends may be artificial.

The biomass of small zooplankton was generally similar to that of large zooplankton in fall (Figure 30), although slightly higher at LL_07. However, in 2013, the biomass of large zooplankton was unusually high at all stations except SG_23, as was also the case in 2016 at HL_06. In all of these cases the high biomass was associated with the presence of salps. The only observable trend was a downward trend in the biomass of small zooplankton at LL_07.  As will be discussed below, this might have been artificial, due to earlier sampling in the latter years.

### _Seasonal distribution and average abundance of the ten most abundant copepod taxa_

Five taxa were among the ten most abundant in both seasons and at all sites (Calanus finmarchicus, Metridia lucens, Microcalanus, Oithona atlantica, Oithona similis) (Figures 31 and 32). O. similis was always the most abundant taxon and was more common in spring than in fall, and more abundant at LL_07 and GULD_03 than at the Gully mouth stations and HL_06 in fall, reflecting its association with colder/shelf waters. Its congener, Oithona atlantica, was similarly abundant at all sites and in both seasons, which was also the case for Metridia lucens and Microcalanus. These three taxa are associated with deep water, with O. atlantica and Microcalanus generally being most abundant near the surface, at least in fall (Head, unpubl. data) and with M. lucens performing diel migration, spending the daytime at depth, and the nighttime in the near surface layers. C. finmarchicus was more abundant in spring than in fall, reflecting different phases of its annual life cycle.

Among the other top ten taxa, Pseudocalanus was abundant at all four sites in spring (Figure 31), but at only LL_07 and GULD_03 in fall (Figure 32). This genus includes four species, which all have shelf/cold-water associations. By contrast, the warm water taxa Clausocalanus and Paracalanus were relatively abundant at all four sites in fall and much less abundant in spring.

Calanus hyperboreus and Temora longicornis were relatively abundant at three sites in spring, but absent in fall. C. hyperboreus is mainly an arctic species, but is present in the Gulf of St Lawrence, overwintering at depth in the Laurentian Channel and reproducing in advance of the spring bloom. In spring-early summer, young stage C. hyperboreus are relatively abundant in near-surface waters, but for only 2-3 months before descending to colder waters as near surface temperatures rise. T. longicornis is also abundant in the Gulf of St Lawrence, which is probably the source for the Scotian Shelf/slope waters.

The shelf-water taxon, Centropages, was relatively abundant during both seasons at GULD_03 and LL_07, while two deep water taxa (Pleuromamma, Oncaea) were relatively abundant only at HL_06 and the Gully mouth stations. Pleuromamma is a warm-water taxon, which is a diel migrant like M. lucens. Oncaea has a cosmopolitan distribution but was among the top ten taxa only at HL_06 and the Gully mouth stations.

Metridia longa was relatively abundant at the Gully stations in spring and fall and at LL_07 in fall. This species is a diel migrant, like its congener M. lucens, although it is associated with colder waters and has a more northerly distribution. Like C. hyperboreus, it is abundant in the Gulf of St Lawrence, the likely source to the study area.

Mecynocera clausi, a warm water taxon, was among the ten most abundant taxa only at HL_06 and only in fall, whereas Scolecithrocella, a cold deep-water taxon, was among the top ten only at LL_07 in spring.

Among these taxa, individuals are relatively large for the two Calanus taxa, the two Metridia species and Pleuromamma, while for the others they are small. Average biomass was estimated for each taxon as the product of individual dry weight and abundance. Dry weights were available for C. finmarchicus, C. hyperboreus, Oithona, and Pseudocalanus  for specimens collected on the Scotian Shelf (Head and Harris 2004), while literature values were used for the other taxa.  For the Calanus species, stage specific dry weights and abundances were used in the calculations, while for the other taxa average dry weights and total taxon abundances were used. The five large taxa contributed on average 89-93% of the biomass of the ten most abundant taxa in spring and 82-93% in fall. The two Oithona taxa combined accounted for <4% of the biomass at all four sites in spring and fall.

### _Relationship between temperature and zooplankton abundance_

Physiological rates of copepods are related to temperature, and some taxa are associated with warmer (offshore, southern) or cooler (shelf/slope, northern) water masses. Furthermore, most of the ten most abundant copepod taxa are more abundant in the near-surface layers than at depth, except for C. fimarchicus in fall (Head unpubl. data). Thus, relationships between in situ near-surface (5 m and 0 - 200 m) temperatures and taxon abundance were examined, as well as abundance trends over time (Tables \@ref(tab:table7) and \@ref(tab:table8)).

Among the significant relationships that emerged, correlations between the abundances of Clausocalanus and Pleuromamma and temperature were consistently positive in spring and fall, reflecting their association with warm/offshore water (Tables \@ref(tab:table7) and \@ref(tab:table8)). By contrast, the abundance of the supposedly warm-water taxon, M. lucens, was positively correlated with 5 m temperature at GULD_03 in spring, but negatively correlated with 0 - 200 m temperature at HL_06 in fall. Otherwise, significant relationships between taxon abundances and near-surface temperatures were negative, and more numerous in fall than in spring. However, the correlations in fall are ambiguous as near-surface temperatures decreased with increasing (later) sampling date between September and December, and due to the seasonal variation in abundance in relation to life cycle stage exhibited by most taxa. In fact the abundances of C. finmarchicus, O. similis and Pseudocalanus were positively correlated with sampling date at LL_07, while Clausocalanus abundance was negatively correlated with sampling date. All four of these relationships are consistent with the observations of the three negative, and one positive, correlations with near surface in situ temperature at LL_07. Thus, temperature and/or seasonal life-cycle effects could be driving the relationships.

April abundances for C. hyperboreus at GULD_03 and for O. similis, Microcalanus and Scolecithrocella at LL_07 decreased over time, possibly due to an increase in sea surface temperatures over time, since the abundances for all four were negatively correlated with near-surface temperature in spring. In fall, as discussed above, differences in sampling dates from year to year mean that the apparent observed trends over time may, or may not, be real.

### _Calanus finmarchicus life cycle and distribution in the Gully region and nearby slope waters_

C. finmarchicus is perhaps the most ecologically important zooplankton species in the Scotian Shelf and slope waters, dominating the biomass for part of the year and serving as food for a variety of commercial fish species, some baleen whales and seabirds. Because of this, and because the species has been studied in some detail, both on the Scotian Shelf and elsewhere, a more extensive discussion of this species is presented in this report than for the other taxa.

Individual C. finmarchicus spend the winter at depth, mostly as pre-adult stage CV copepodites, in a dormant state (diapause) with reduced metabolic activity. In early spring, these CVs ascend to the surface, mature to adulthood, mate and start to reproduce. Growth and development to the CV stage proceed during late spring and early summer, with the CVs descending in late summer and fall to overwinter and complete the life cycle. Thus, C. finmarchicus populations collected during spring AZMP cruises are comprised of mixtures of overwintered maturing (CV) and matured (adult) individuals and young stages (CI-CIVs) of the new year’s generation. The timing of the onset of reproduction is related to the timing of the spring bloom, because females need to feed on phytoplankton to produce eggs, but temperature and food (phytoplankton) conditions also affect rates of reproduction, growth and development. Samples collected in fall, by contrast, are dominated by CVs with some CIVs. The CVs are mainly at their overwintering depths when fall AZMP cruises take place, whereas the CIVs are at slightly shallower depths (Head unpubl. data), presumably trying to feed and reach the CV stage before descending. Overwintering areas that are the source of adults and their offspring to the Scotian Shelf region include the Gulf of St Lawrence, the shelf basins and the slope waters.

AZMP zooplankton sample analysis includes identification to stage and enumeration of all C. finmarchicus stages. In spring, the abundance, reported in percentage, of early copepodite stages (CI-III) in C. finmarchicus populations can be used as an index of the state of population development (Population Development Index, PDI). Following reproduction, this proportion will rise, as eggs develop into CI-III copepodites and then fall again as individuals reach stages CIV and CV.

It seems likely that PDI values observed during AZMP missions in spring will be influenced by the timing of the spring bloom relative to the sampling date, and by temperature, so some exploratory analyses of these relationships was undertaken.  Plots of the PDI versus the difference between sampling date and date of bloom initiation gave somewhat different patterns at HL_06 and LL_07 (Figure 33). At HL_06 sampling occurred before bloom initiation in two years, and the PDI was low. Highest PDI values were observed when sampling was between 20 and 40 days after bloom initiation and values dropped thereafter. At LL_07 sampling was always after the bloom had started and while PDI values were significantly lower when sampling was < 20 days after bloom initiation than when it was between 27 and 40 days after bloom initiation, and PDI values remained high for another 30 days thereafter. In addition, at HL_06 the PDI decreased with increasing temperature, while at LL_07 it increased with increasing temperature. Clearly, interpretation of inter-annual variations in observed PDIs requires a more sophisticated approach (e.g. including life history modelling and advective) than the one taken here.

In fall at LL_07 and HL_06 most C. finmarchicus are CVs (averages 78 and 88% of total abundance, respectively), with CIVs accounting for most of the rest (average 15%, at both stations) (Figure 34). These populations represent the season’s accumulated annual production. At GULD_03, CVs and CVIs together accounted for, on average, 83% of the population, with CI-IIIs making up another 13%, indicating ongoing low level reproduction and development.

At HL_06 and GULD_03, CV abundance increased and decreased, respectively, with increasing (later) sampling date, although neither trend was significant. At LL_07, however, if one especially late sampling date (DoY 336, Dec 1, 2014) was excluded, there was a significant positive correlation between CV abundance and sampling date. CIV abundances were low at all stations and showed no significant trends with sampling date. In addition, CV abundances were not related to temperature at the depths of their maximum abundance, which were 400 - 600 m at HL_06 and 200 - 400 m at GULD_03 and LL_07 (Head unpubl. data), and there were no trends in abundance over the years at any of the sampling sites.

Overall, the observations of C. finmarchicus populations in fall were consistent with the idea that CVs are accumulating at their overwintering depths until at least early November (approximately DoY 310). While sampling date appears to have some influence, it is not the only factor determining CV abundance, because CVs are long-lived and accumulate at depth over several months, so that transport and mortality will have important effects, which cannot be evaluated here.

\clearpage
