# DISCUSSION {#sec:discussion}

Since its establishment in 2004, the Gully MPA has been the focus of a number of targeted studies aimed at describing its physical and chemical properties and mean circulation patterns (@strain_2005; @greenan_2014; @shan_2014a; @shan_2014b), mainly for the purpose of providing quantitative evidence of physical and/or chemical characteristics (e.g. elevated nutrient and chlorophyll concentrations, upwelling and gyre-like circulation) that may support elevated levels of productivity and thus the high biodiversity observed in the canyon. However, since the analyses of @greenan_2014 conducted on mooring and CTD observations collected over a 16-month period from April 2006 to August 2007, little has been done to assess changes in the physical, chemical, and biological state of the Gully, and to date, no analyses have been conducted using datasets collected over a longer time period. This report represents the first compilation and preliminary analyses of the oceanographic conditions of the Gully using data collected by the Maritime Region AZMP. Such analyses provide a basis for a quantitative baseline for which to evaluate future oceanographic change within the MPA. The discussion section is framed around the evaluation of aspects of oceanographic indicators 21, 22, and 27 [@kenchington_2010] for which the AZMP routinely collect data. The results and conclusions drawn from our assessment of indicators 23 (physical and biological sea surface properties from satellite measurements) and 26 (phytoplankton dynamics) are also discussed herein. We conclude with recommendations on a revised sampling scheme of the Gully MPA and frequency of reporting to ensure effective oceanographic monitoring of this unique ecosystem.

## **Evaluation of temperature, salinity, oxygen, nutrients, and chlorophyll within the Gully MPA**

Our analysis of the mean vertical structure of temperature (Figures 5, 10) at each of the four AZMP fixed stations in the Gully showed characteristically different patterns between the spring and fall seasons, consistent with broad-scale patterns observed in the Atlantic zone [@dfo_2019]. In spring, a 3-layer vertical structure in water mass properties was featured on all stations, with relatively cooler, fresher near-surface mixed layers, warmer, saltier intermediate (100 - 400 m) layers, and cooler deeper layers. This is consistent with the 3-layer structure observed in the Gully in April 2006 by @greenan_2014. The authors noted that the upper 100 m featured cooler but more variable temperatures, likely resulting from annual changes in freshwater inflow and heat flux. The presence of a warm, saline and low-oxygen saturation layer between 100 and 350 m was attributed to the presence of Warm Slope Water (WSW), characterized by temperature and salinity ranges between 9 - 13°C and 34.73 - 35.56, respectively [see @greenan_2014], and references therein). The warmer intermediate layer (100 - 400 m) observed in our study was associated with variable temperatures and salinities (indicated by the relatively high 95% confidence interval values; red dashed lines in Figs. 5, 6), suggesting that the presence and/or intensity of the WSW that characterizes this layer varies from year to year. Alternatively, fluctuations in water column properties may be attributed to warm-water eddies impinging on the shelf break. The anomalously warm temperatures observed on Gully mouth station SG_28 in spring 2018 (Figure 9) were also observed on the offshore Louisbourg, Browns Bank, and Halifax sections [@hebert_2020], where surface temperatures in excess of 14ºC were well mixed from the surface to 200 m depth. This phenomenon was thought to be caused by a Gulf Stream eddy impinging closer to the shelf break than in previous years, an occurrence which is rare but may result in higher-than-average water temperatures throughout the water column. Why this feature was not observed on the other stations located across the mouth of the Gully remains unknown, but is likely due to the more southwesterly position of SG_28 and closer proximity to the Gulf Stream, than stations GULD_04 and SG_23.

The cooler, deeper (> 400 m) layers observed in the Gully by [@greenan_2014] were attributed to a dominance of Labrador Slope Water (LSW), which is characterized by higher dissolved oxygen and temperatures and salinities ranging between 4 - 9ºC and 34.3 - 35, respectively. In fall (September-October), surface waters (0 - 50 m) were consistently above 10⁰C in most years, and the warm and saltier intermediate (100 - 400 m) layer was still present at all stations. Elsewhere on the Scotian Shelf, the surface layer deepens and cools in late fall/early winter due to wind-driven vertical mixing (DFO 2019), a pattern which would not be captured in our spring and early fall (September to October) delimited datasets.

Inorganic nutrient (nitrate, phosphate, silicate) concentrations in the Gully showed similar patterns with depth between seasons and among stations. Mean nitrate and phosphate concentrations peaked at 250 m, while silicate peaked at 250 or 500 m at all stations and seasons. A more detailed examination of nutrient concentrations using data collected from the 1960’s onward [@strain_2005] demonstrated higher nitrate, silicate and phosphate levels at the head of the Gully compared to the mouth, and on the Sable Bank side compared to the Banquereau side. While no east-to-west trends (i.e. across the Gully mouth stations) were observed for any of the three nutrients in either season, a north-south pattern was evident, where nitrate, phosphate, and silicate were lowest at the Gully head station (GULD_03) compared to the Gully mouth stations in both spring and fall.

In contrast, the spatial distribution of chlorophyll a concentrations within the Gully showed higher chlorophyll a concentrations occurring at the Gully head in spring. @greenan_2014 suggested that the mean transport towards the head of the Gully and increased upwelling velocity over the inner portion of the canyon should result in a significant vertical nitrate flux and enhanced chlorophyll concentrations in the upper 200 m. While this may explain why chlorophyll a concentrations were higher at station GULD_03 than at mouth, any enhancement in local productivity in the upper 200 m of the canyon would be quickly advected by the southwestward current that flows relatively unimpeded over the upper 200 m of the canyon. This advection to the southwest may consequently result in elevated levels of productivity downstream of the Gully MPA [@greenan_2014]. Evaluation of mean spring and fall nutrient concentrations between the four AZMP stations in the Gully and stations both upstream (LL_07) and downstream (HL_06) of the MPA (Figure 22) showed no significant differences in nutrient concentrations between the Gully and downstream station HL_06. While differences in chlorophyll a concentration between the Gully and adjacent areas were not evaluated in this report, no differences were observed between the standing crop of chlorophyll a measured in the canyon in 2006 and 2007 and those recorded on the adjacent shelf from archived data [@greenan_2014]. Overall, our evaluation of nutrient concentrations between the Gully and adjacent areas do not provide any evidence that primary production in the Gully MPA is enhanced relative to that of nearby areas, similar to the conclusions of @greenan_2014.


## **Patterns in remote-sensed sea surface chlorophyll, temperature, and zooplankton biomass, abundance, and composition in the Gully and areas upstream and downstream**

The results presented in this report demonstrate the importance of using both remotely-sensed and in situ measurements of chlorophyll concentration to monitor and understand phytoplankton distribution, variability, and trends in the Gully region. Near-surface chlorophyll a concentrations, as observed by satellite-mounted sensors, show that in the Gully and nearby regions phytoplankton spring blooms can start as early as late February and as late as the end of April, and can last for as few as 10 days or as many as 40 days. Furthermore, they show that even within years, the timing, intensity and duration of spring blooms generally vary among different regions of the Scotian Shelf. Thus, AZMP sampling missions, which are typically in April in spring, may or may not encounter bloom conditions on the Scotian Shelf, and the snapshots they provide are inadequate in describing the dynamics of spring blooms, which are important to the production cycles of the consumers (i.e. zooplankton) that depend on them. On the other hand, collection of water samples is essential to observe events in the sub-surface layers, especially in summer and early fall, when peaks of chlorophyll concentration are at 30 - 50 m, and primary production rates are highest.

For the 1998 - 2018 period:

1.	Remotely-sensed measurements of SSC showed no trends in annual average values in the Gully or nearby regions, nor in any of the four metrics used to describe the spring bloom dynamics (start date, amplitude, duration, magnitude)
2.	Inter-annual variability was high for these variables, but there were no obvious links to near-surface temperatures
3.	In situ measurements of near-surface chlorophyll were well correlated with SSC measurements for three satellite areas in the Gully MPA and the slope waters upstream and downstream of the Gully mouth
4.	Consistent with observations elsewhere, relative to in situ chlorophyll concentrations, SSC values were underestimated at high in situ chlorophyll concentrations, and overestimated at low in situ chlorophyll concentrations

Finally, there are data on the detailed pigment composition of in situ surface samples that give information on phytoplankton taxonomic composition that have not been examined for this report. While phytoplankton community composition is encompassed by oceanographic indicator 26 (Kenchington 2010), the analysis of both phytoplankton production and community composition are considered more research-focused and are not routinely evaluated or reported by the AZMP.

Unlike phytoplankton, zooplankton persist in the water column for periods of weeks or months, although the life cycles of most species are linked to the annual cycles of phytoplankton production. As well, since samples are subjected to taxonomic analysis, species with known water mass associations can be used as indicators of past hydrographic events.

For the 1998 - 2018 period:

1.	The biomass of small (<1 cm) zooplankton at stations in the Gully and nearby slope waters was generally higher than that of large (>1 cm) zooplankton in spring, and similar in fall. Anomalously high values were observed for large zooplankton at most stations in 2013 in fall, and occasionally in spring. In fall 2013 the high values were associated with salps, while in spring they were caused by salps or large decapods
2.	Zooplankton communities in the Gully and nearby slope waters were dominated by copepods (>80% of all organisms), with the ten most abundant taxa at each station accounting for >60% of all copepods in fall and >78% in spring
3.	Within the Gully most copepod taxa had shelf/cool water associations, while in the slope waters offshore/warm water taxa are also present
4.	Few individual taxa have shown discernable trends in abundance over time in spring or fall, and those that have appear to be related to temperature trends and are consistent with known associations between individual taxa and different water masses
5.	Apparent relationships between taxon abundances and near-surface temperatures in fall are ambiguous, since sampling dates have varied between September and December, a period during which important life cycle events may occur, while near-surface temperatures are decreasing
6.	The ecologically significant species, Calanus finmarchicus, was among the ten most abundant copepod taxa at all stations in spring and fall, contributing >27% of the biomass in spring and >17% in fall
7.	Proportions of young stages (CI-III) C. finmarchicus in April increased with increasing near-surface temperature at LL_07 but decreased with increasing temperature at HL_06 and appeared to be influenced by the timing of sampling relative to the timing of the start of the spring bloom 
8.	Abundances of late stage (CV) C. finmarchicus at HL_06 and LL_07 in fall increased with increasing (later) sampling date and were not related to temperature at the depths of maximum abundance (400 - 600 m at HL_06, 200 - 400 m at LL_07 and GULD_03)

Here,  zooplankton data derived from vertical net hauls has been used to examine trends in spring and fall biomass and in the abundances of the most abundant members of the mesozooplankton. Another group, the macrozooplankton, includes larger active swimmers, such as euphausiids (krill), which can avoid capture by vertically-towed nets.  Euphausiids can be captured by devices such as the BIONESS and samples have been collected at GULD_03 during spring and/or fall AZMP cruises since 1997. Since krill are distributed in patches, it is unlikely that sampling at one station would give an adequate estimate of their abundance in the Gully as a whole. Better estimates could be obtained using acoustic measurements collected from towed or moored devices. Acoustic surveys were conducted during previous AZMP cruises (Harrison and Fenton 1998), but have long been discontinued, and were only conducted in spring and fall. Deployment of one or more multi-frequency acoustic moorings in the Gully could be used to make year-round observations of zooplankton biomass in the same way that satellites are used to observe phytoplankton biomass. We recommend that the acquisition and deployment of such a device be considered in future monitoring plans for more effective monitoring the zooplankton communities of the MPA. 


## **Modification of the AZMP’s existing sampling scheme of the Gully MPA**

The AZMP’s four standard sections in the Maritimes Region were initially designed to measure the major oceanographic processes that characterize the Scotian Shelf: inflow/outflow of the Gulf of St. Lawrence (Cabot Strait), the eastern shelf climate where Gulf of St. Lawrence water dominates but slope water has a significant influence (Louisbourg Line), central shelf dynamics where slope water exerts a significant influence in its deep inner basins (Halifax Line), and the western shelf climate where tidal mixing has a significant influence on water mass structure (Browns Bank; Therriault et al. 1998). At present, the four Gully stations are not considered part of the AZMP’s standard or ‘core’ sections/stations, putting them at greater risk of not being occupied during the program’s biannual surveys should program duration be impacted. Our qualitative evaluation of the conditions within the Gully versus those upstream and downstream of the canyon (Figure 13) showed comparable water column properties (temperature and salinity) between the Louisbourg Line station LL_07 and the Gully head station (GULD_03). Dissolved oxygen concentration at LL_07 was more comparable to that of the three Gully mouth stations. In contrast, HL_06 was relatively warmer, more saline, and oxygen-poor compared to LL_07 and the four Gully stations. Station HL_06 is situated further to the southwest than the Gully, and on the eastern flank of an area colloquially referred to as the ‘Scotian Gulf’, an inlet formed by a cross-shelf channel situated between Emerald and LaHave Banks, which opens up into the LaHave and Emerald Basins on the inner Scotian Shelf. The Scotian Gulf and its inner basins experience regular ingression of WSW, which is considered the dominant flow feature of Emerald and LaHave Basins (Smith et al. 1978). The greater influence of WSW in this region likely explains the warmer, more saline and oxygen-poor water column properties observed at station HL_06 compared to upstream areas. These results collectively suggest that core AZMP stations upstream (i.e. LL_07), but not downstream (HL_06), of the Gully MPA may serve as a proxy for the conditions occurring within the canyon proper. During surveys where the Gully MPA is not occupied, data collected on the off-shelf Louisbourg Line should be evaluated and any short-term or rapid changes in oceanographic conditions noted as potentially having an impact on the ecosystems of the Gully MPA.

Our results showed that the water column properties across the three Gully mouth stations were comparable at similar depths, while conditions within the canyon proper near the head of the Gully (station GULD_03) were relatively dissimilar. The latter is influenced by a greater contribution of shelf water, leading to cooler, fresher waters throughout the water column compared to the three stations situated beyond the shelf break. The similarities between the three Gully mouth stations points to a redundancy in the AZMP’s current sampling scheme of the MPA. Located above the canyon thalweg, station GULD_04 is the deepest of all four stations and therefore better captures the full water column over the canyon compared to stations SG_23 and SG_28 located on the adjacent flanks. We recommend that the existing sampling scheme of the MPA is modified and stations SG_23 and SG_28 are repositioned over the thalweg of the canyon, or in other areas of biological relevance.

The AZMP’s four fixed stations in the Gully were selected without the boundaries of the MPA and its three management zones in mind. While any management boundaries may be considered arbitrary with respect to large-scale hydrographic processes, the water depth and topography of each of the 3 zones differs, as do their associated benthic communities. The existing AZMP fixed stations currently occupy Gully MPA Management Zones 1 (SG_28 and GULD_04) and 2 (SG_23 and GULD_03). While Zones 1 and 2 represent the areas of greatest conservation concern within the MPA, Zone 3 is considered an ‘MPA Transition Zone’ (DFO 2017), encompassing the remainder of the MPA. The eastern and western polygons that comprise Zone 3 are situated over sandy banks shallower than 300 m on Banquereau and Sable Island Bank, respectively. Given its shallow depth, this zone is subjected to a high variability in oceanographic properties and is regularly influenced by storm events, a natural source of disturbance. As a result, a wider range of commercial and recreational activities are permitted within this zone. Although Zone 3 is of lowest conservation concern, the physical and biological processes that govern this zone may also exert influence on those occurring within the canyon proper. For instance, some of the primary productivity measured in Zone 3 has been noted to move into and influence the deeper portions of the canyon (DFO 2017). Zone 3 is also considered a key migratory route for fish moving into the canyon, and Zone 3 East is known for being overwintering grounds for several species of commercially important groundfish (DFO 2017). However, oceanographic monitoring of Zone 3 would likely add little value to the AZMP’s existing sampling scheme of the MPA. The southwestward current that flows over the Gully down to canyon rim depths (approximately 200 m), relatively unimpeded by the canyon topography (Greenan et al. 2014), suggests that the conditions in Zone 3 would likely be similar to the upper layers of station GULD_03 located near the canyon thalweg. Furthermore, hydrographic data collected at similar depths on Banquereau and Sable Island Bank by the AZMP during its participation in DFO’s ecosystem research vessel trawl surveys may also serve as a proxy for the conditions governing Zone 3. Increasing the number of sampling stations in the Gully MPA would require a commitment of increased support in terms of ship time and funding for sample and data analysis. Additional AZMP monitoring stations could be considered for future sampling in Zone 3 or elsewhere in the canyon should evidence of their biological significance become available.


## **Evaluating temporal changes in physical, chemical, and biological oceanographic conditions of the Gully MPA**

In 2015, an assessment of the available data contributing towards the 47 Gully monitoring indicators was conducted by both government and non-government scientists [see @allard_2015] with the purpose of evaluating whether the available data met the indicator monitoring requirements. While the AZMP’s data collection scheme of the Gully was described, analyses of these data were not conducted, and long-term trends in oceanographic conditions in the canyon were inferred from nearby AZMP standard sections (Halifax, Louisbourg, Browns Bank, and Cabot Strait) where baseline values were available. Climatological ‘normals’ that serve as benchmarks to which recent oceanographic observations can be compared, are generally calculated over 30-year periods. While this convention is in part based on a statistical guideline that a minimum of 30 data points are required to reliably construct a mean, a 30-year time period ensures that any patterns reflect the long-term, or at least multi-decadal, climatology of the system, and not anomalous environmental conditions. A total of 37 and 45 CTD profiles were collected in spring and fall, respectively, over the 19-year period over which the AZMP has sampled the Gully, indicating that the dataset is still insufficient for the calculation of a meaningful climatology. A similar conclusion was drawn for the available data collected in the more recently-established St. Anns Bank MPA [@layton_2020], for which the AZMP began conducting dedicated sampling in 2011 after the area was designated as an Area of Interest. As the AZMP program is less than 30 years old, annual reporting on changes in hydrographic conditions on the Scotian Shelf are presented in terms of anomalies (standard and normalized) relative to a 30-year base period from 1981 to 2010 using data collated from multiple sources [@hebert_2020]. However, for chemical (e.g. nutrients) and biological (e.g. zooplankton abundance) analyses for which there are shorter time series and fewer data available, anomalies are evaluated against a 16-year reference period calculated from 1999 to 2015 [@casault_2020]. While this approach was not taken here, we suggest that per-station reference climatologies be calculated for each of the four fixed stations in the Gully following standard AZMP procedures (i.e. mean seasonal temperature at various depth intervals over the time period available), and future anomalies be generated and evaluated against these climatologies in subsequent assessments of the oceanographic conditions of the MPA.

The Scotian Shelf lies at a confluence of two large ocean gyre currents: the subpolar Labrador Current and subtropical Gulf Stream (Loder et al. 1998), and the influence of each on the region varies as a result of multi-decadal fluctuations in the Atlantic Multi-Decadal Oscillation (@drinkwater_1998; @knight_2005). This results in high inter-annual and multi-decadal variability in water mass characteristics on the Scotian Shelf that may mask real trends resulting from climate change. While a conclusion of the last assessment of datasets contributing to the oceanographic monitoring of the Gully [@allard_2015] was that no long-term trends in conditions had been detected over the history of AZMP sampling, observations from the program made since then suggest that more recently-detected changes in physical, chemical, and biological conditions on the Scotian Shelf are persisting [@casault_2020]. Surface and deep silicate and phosphate inventories have shown a declining trend since 2014, with deep nitrate inventories also showing below average values over the last three years across the region. Lower abundances of large phytoplankton (diatoms), and declining zooplankton biomass and C. finmarchicus abundance across the Scotian Shelf have also been noted. Above-normal abundances of offshore copepods on the Scotian Shelf, particularly Oithona atlantica as observed at station Halifax-2, suggest a greater influence of offshore waters in more recent years [@casault_2020].

Similar to other locations on the Scotian Shelf, water mass characteristics in the Gully MPA were highly variable between seasons and years. The high inter-annual variability observed in the upper 100 m of the Gully mouth stations in fall suggests that a much longer time series than that analyzed here is required in order to detect changes in fall conditions resulting from anthropogenic climate change. Furthermore, the occurrence of anomalous events, such as warm-core eddy impingement on the Scotian Shelf (see Figure 9 and Results section), may confound the detection of trends in datasets collected on only a biannual basis. Deployment of moored devices for the collection of year-round observations would greatly enhance the program’s ability to effectively monitor temporal changes in the Gully MPA. Nonetheless, despite our limited, seasonally-defined time series, our results showed statistically significant, increasing trends in spring temperatures at subsurface and intermediate depths at all stations (Figure 10 and Table 5). Upper-ocean temperatures have increased in the northwest Atlantic over the last century, consistent with the global trend of increasing sea surface temperatures as a result of anthropogenic climate change [@bush_2019]. Under future climate change, the east-to-west flowing shelf break current originating from the Labrador Sea is also projected to weaken, while the influence of Warm Slope Water in the region is projected to increase [@saba_2016]. Given that the time series from which these analyses were based are relatively short, our observed trends should be considered in the context of longer-term trends on the Scotian Shelf and Gulf of Maine to determine their overall significance. Nonetheless, our results highlight the need to conduct regular, dedicated reporting on the oceanographic conditions of the Gully MPA. While annual reporting on the conditions observed elsewhere on the Scotian Shelf (e.g. Louisbourg Line station LL_07) may generally inform on anomalous events or years that may impact the ecosystems of the MPA, we recommend that dedicated oceanographic reporting on the Gully be conducted every 5 years in order to effectively track temporal changes within the MPA, and ensure that any alterations of its physical, chemical, or biological state are being considered in current conservation management strategies aimed at protecting its unique ecosystems.

\clearpage
