# SUMMARY {#sec:summary}

Consistent with observations from other areas of the Scotian Shelf, the water mass properties observed on the four AZMP fixed stations in the Gully were highly variable over the 19-year period evaluated. Data collected during the AZMP biannual surveys augmented with observations from year-round moorings would greatly enhance the program’s its ability to effectively monitor temporal changes in the MPA. Nonetheless, evaluation of the AZMP’s biannual data revealed increasing trends in spring temperatures at all four fixed stations in the Gully MPA. This highlights the need to conduct dedicated, regular (every 5 years) reporting on the oceanographic characteristics of the MPA for consideration in current conservation management strategies.

Consistencies in the oceanographic conditions evaluated at the three AZMP stations across the Gully mouth highlight redundancies in the AZMP’s existing sampling scheme of the MPA. While monitoring should continue at station GULD_03 near the Gully head, and GULD_04 located at the Gully mouth, continued monitoring at stations SG_23 and SG_28 provide little additional value. We recommend that these stations are redistributed elsewhere in the canyon, either over the thalweg to better monitor the canyon’s flow-through system, or at the location of areas of biological significance.

While there were no apparent trends in nutrient or chlorophyll concentrations over time, either within or among stations, the high inter-annual variability in zooplankton abundance and composition appeared to be associated with the presence of different water masses within the Gully MPA. However, these trends were confounded by differences in the timing of sampling and biological events (e.g. the timing of the spring bloom). Effort should be placed on conducting the spring and fall biannual surveys during the same month (April in spring, and late September or early October in fall) each year in order to reduce these confounding effects.

\clearpage
