# ACKNOWLEDGEMENTS {#sec:acknowledgements}

The completion of this project could not have been achieved without the input, advice and helpful suggestions of our many colleagues at the Bedford Institute of Oceanography. We thank Tana Worcester, Catalina Gomez, Gordana Lazin, Ryan Stanley, Phillip Greyson, and Nick Jeffery for their ideas, advice and guidance during the development and data synthesis stages of this project. We thank physical oceanographers Dave Hebert, Blair Greenan, Chantelle Layton, and Benoit Casault for their suggestions on data analysis and interpretation.
We thank the authors of R ‘csasdown’ for their technical assistance during the generation of this report.
We would also like to thank all sea-going, field operations, data management personnel for their support during the collection and processing of data collected during the AZMP biannual surveys. We also thank the captains and crew of the Canadian Coast Guard vessels and chartered platforms used to conduct the surveys over the years. 

We thank reviewers Chantelle Layton and Nick Jeffery (both of DFO) for their reviews of this publication.

Funding for this project was provided by DFO’s National Conservation Plan (NCP).

\clearpage
