
\begin{landscapepage}
\hypertarget{sec:tables}{%
\section{TABLES}\label{sec:tables}}

```{r table1, results="asis", include=TRUE, echo=FALSE}

#array stretch increases row height
cat("\\renewcommand{\\arraystretch}{2}   \n")

# Load the CTD data acquired at the four monitoring stations.
load("data/monitoringSitesAllCtd.RData")
load("data/monitoringSitesAllCtdPrograms.RData")

# Load the CTD data acquired at the four monitoring stations (only used to 
# produce the CTD table to identify casts for analysis.
# load("data/monitoringSitesCtdForAnalysis.RData")
# load("data/monitoringSitesCtdForAnalysisPrograms.RData")

# Data sets.
dsets <- c("guld03_ctd", "guld04_ctd", "sg23_ctd", "sg28_ctd")

# Modify the station name metadata attribute to be the appropriate Gully
# monitoring station name in each ctd object of each data set.
for (j in 1:4) {
  ds <- dsets[j]
  dset <- eval(parse(text=paste0(ds)))
  nctds <- length(dset)
  bits <- unlist(str_split(ds, "_"))
  sName <- bits[1]
  # Note that underscore characters in latex output must be escaped.
  if (sName == "guld03") stn <- "GULD\\_03"
  else if (sName == "guld04") stn <- "GULD\\_04"
  else if (sName == "sg23") stn <- "SG\\_23"
  else if (sName == "sg28") stn <- "SG\\_28"
  for (z in 1:nctds) {
    dset[[z]]@metadata$stationName <- stn
  }
  eval(parse(text=paste0(ds, " <- dset")))
}

# Combine the four lists of ctd objects into a new list so that the table that
# will to be produced will have all of the data listed by cruise in
# chronological order.
gullyCTD <- c(guld03_ctd, guld04_ctd, sg23_ctd, sg28_ctd)
gullyCTDprograms <- c(guld03_programs, guld04_programs, sg23_programs, sg28_programs)

# Get all of the start times for all Gully CTD objects.
startTime <- as.character(as.POSIXct(unlist(lapply(gullyCTD, function(k) k[['startTime']])),
                                     origin = '1970-01-01',
                                     tz = 'UTC'))

# Get the sorted indices of the list so that the list can be sorted in
# chronological order.
ix <- order(startTime)

# Put the CTD objects into chronological order.
gullyCTD <- gullyCTD[ix]
gullyCTDprograms <- gullyCTDprograms[ix]

# Get the metadata required to build the table for the report.
cruiseNumber <- unlist(lapply(gullyCTD, function(k) k@metadata$cruiseNumber))
stationName <- unlist(lapply(gullyCTD, function(k) k@metadata$stationName))
Event <- unlist(lapply(gullyCTD, function(k) k@metadata$eventNumber))
Survey <- unlist(lapply(gullyCTDprograms, function(k) k))
Longitude <- unlist(lapply(gullyCTD, function(k) k[['longitude']][1]))
Latitude <- unlist(lapply(gullyCTD, function(k) k[['latitude']][1]))
Maximum_Depth <- unlist(lapply(gullyCTD, function(k) k[['depthMax']]))
Start_Date_Time <- startTime[ix]

# Replace the cruise number 99054 with HUD1999054.
cruiseNumber[1] = "HUD1999054"

# Remove data for NED2005004
rx1 <- which(cruiseNumber == "NED2005004")

# Remove data for HUD2007045, Event 130.
rx2 <- which((cruiseNumber == "HUD2007045") & (Event == "130"))

# Remove data for TEL2010900
rx3 <- which(cruiseNumber == "TEL2010900")

# Combine list of rows to remove
dx <- c(rx1,rx2,rx3)

# Remove rows from arrays
cruiseNumber <- cruiseNumber[-dx]
stationName <- stationName[-dx]
Event <- Event[-dx]
Survey <- Survey[-dx]
Longitude <- Longitude[-dx]
Latitude <- Latitude[-dx]
Maximum_Depth <- Maximum_Depth[-dx]
Start_Date_Time <- Start_Date_Time[-dx]

# Replace remaining "Non-AZMP" with "Greenan et al. (2014)"
sx <- which(Survey == "Non-AZMP")
Survey[sx] <- "Greenan et al. (2014)"

# Get the name of the month  when the profile occurred.  Change the output to a
# character array from "ordered" "factor".
mon <- month(Start_Date_Time, label = TRUE, abbr = FALSE)
mon <- as.character(mon)

# Change the maximum depth from a number to a string without any decimals.
Maximum_Depth <- as.character(round(Maximum_Depth,0))

header1 <- c("Cruise", "Station", "Event", "Survey", "Month", "Longitude (DD)", 
            "Latitude (DD)", "Maximum Depth (m)", "Date/Start Time (UTC)")

ctable1 <- tibble(cruiseNumber, stationName, Event, Survey, mon, Longitude, Latitude, Maximum_Depth, Start_Date_Time)

colnames(ctable1) <- header1

kbl(ctable1,
    booktab = TRUE,
    linesep = "",
    longtable = TRUE,
    format = "latex",
    escape = FALSE,
    align = "ccccccccc",
    caption = "Summary of CTD profiles collected at the four AZMP fixed stations in the Gully (SG\\_23, SG\\_28, GULD\\_03, and GULD\\_04) between 1999 to 2018. Survey, month of sampling, station coordinates in decimal degrees (DD), maximum depth of the CTD package, and the date of collection/start time in UTC is shown. Only profiles collected in April (37 profiles; representative of spring), September and October (45 profiles, representative of fall) are included in the analyses presented in this report.") %>%
  # Make the header row bold text
  kableExtra::row_spec(0, bold = TRUE) %>%
  # Repeat the header on multiple pages and make the font size 10.
  kableExtra::kable_styling(latex_options = "repeat_header", repeat_header_method = "replace", font_size = 11, full_width = FALSE) %>%
  # Alternate the rows with different colors to make it easier to read.
  kableExtra::kable_styling(latex_options = c("striped")) %>%
  kableExtra::column_spec(1, width = "6em") %>%
  kableExtra::column_spec(2, width = "5em") %>%
  kableExtra::column_spec(3, width = "3em") %>%
  kableExtra::column_spec(4, width = "6em") %>%
  kableExtra::column_spec(5, width = "5em") %>%
  kableExtra::column_spec(6, width = "5em") %>%
  kableExtra::column_spec(7, width = "5em") %>%
  kableExtra::column_spec(8, width = "5em") %>%
  kableExtra::column_spec(9, width = "9em")

```
\end{landscapepage}

\clearpage


```{r table2, results="asis", include=TRUE, echo=FALSE}

seasons <- c(rep("Spring", 4), rep("Fall", 4))
stations <- c("GULD\\_03", "GULD\\_04", "SG\\_23", "SG\\_28", "GULD\\_03", "GULD\\_04", "SG\\_23", "SG\\_28")
nprof <- c(12, 10, 7, 8, 15, 11, 9, 10)
minYears <- c(2000, 2000, 2008, 2008, 2000, 2000, 2007, 2007)
maxYears <- c(2018, 2018, 2017, 2018, 2018, 2018, 2018, 2018)

header2 <- c("Season", "Station", "Number of CTD Profiles", "Min", "Max")

ctable2 <- tibble(seasons, stations, nprof, minYears, maxYears)

colnames(ctable2) <- header2

# csasdown::csas_table(ctable2,
#                      font_size = 12,
#                      format = "latex",
#                      align = c("l","l","c","c","c"),
#                      caption = "Number of CTD profiles collected in spring and fall at each of the four AZMP fixed stations in the Gully MPA. The range in year of collection is also shown for each station and season.") %>% 
#   kableExtra::add_header_above(c(" ", " ", " ", "Year" = 2), bold = TRUE)
#   # kableExtra::collapse_rows(columns = 1)

kbl(ctable2, 
    booktabs = TRUE,
    linesep = "",
    longtable = TRUE,
    format = "latex",
    escape = FALSE,
    align = "llcccc",
    caption = "Number of CTD profiles collected in spring and fall at each of the four AZMP fixed stations in the Gully MPA. The range in year of collection is also shown for each station and season.") %>% 
  kableExtra::add_header_above(c(" ", " ", " ", "Year" = 2), bold = TRUE, font_size = 12) %>%
  kableExtra::row_spec(0, bold = TRUE, font_size = 12) %>%
  kableExtra::collapse_rows(columns = 1, latex_hline = "major", valign = "middle")

```

\clearpage


\begin{landscapepage}

```{r table3, results="asis", include=TRUE, echo=FALSE}

stations <- c(rep("GULD\\_03", 11), rep("SG\\_28", 13), rep("SG\\_23", 13), rep("GULD\\_04", 14))
# stations <- c(rep("GULD_03", 11), rep("SG_28", 13), rep("SG_23", 13), rep("GULD_04", 14))
approxDepth <- c(rep("$\\sim$ 445 m", 11), rep("$\\sim$ 804 m", 13), rep("$\\sim$ 1102 m", 13), rep("$\\sim$ 1914 m", 14))
nominalDepth <- c(c("BTM", "250", "100", "80", "60", "50", "40", "30", "20", "10", "1"), rep(c("BTM", "750", "500", "250", "100", "80", "60", "50", "40", "30", "20", "10", "1"), 2), c("BTM", "1500", "750", "500", "250", "100", "80", "60", "50", "40", "30", "20", "10", "1"))

# Get the number of rows in the table.
nx <- length(nominalDepth)

# Coerce the nominalDepth array to numeric so it is easier to find the indices 
# for the depths where the different parameters were sampled.
ndepth <- as.numeric(nominalDepth)

# Create arrays for the parameter columns to indicate where samples were taken
chl <- rep("", nx)
ix1 <- which(ndepth <= 100)
chl[ix1] <- "XX"
nuts <- rep("XX", nx)
sal <- rep("", nx)
ix2 <- which((nominalDepth == "BTM") | (nominalDepth == "250") | (nominalDepth == "10"))
sal[ix2] <- "X"
oxy <- sal
oxy[c(1,23,25,50)] <- "XX"

pco2 <- rep("", nx)
ix3 <- which(nominalDepth == "BTM")
pco2[ix3] <- "X"
ix4 <- stations == "GULD\\_04"
ix5 <- which(stations == "GULD\\_04")
g4nd <- nominalDepth[ix4]
ix6 <- which((g4nd == "1500") | (g4nd == "500") | (g4nd == "100") | (g4nd == "10") | (g4nd == "1"))
pco2[ix5[ix6]] <- "X"
tic <- pco2
poc <- rep("", nx)
ix7 <- which(nominalDepth == "1")
poc[ix7] <- "XX"
hplc <- rep("", nx)
hplc[ix7] <- "X"
abs <- hplc
cyto <- rep("XX", nx)
cyto[c(1,2,12,13,15,25,26,28,38,40,42,47)] <- ""

# Create the table header
header3 <- c("Station", "Station Depth", "Nominal Depth", "CHL", "NUTS", "SAL", "O\\textsubscript{2}", "pCO\\textsubscript{2}", "TIC/TA", "POC", "HPLC", "ABS", "CYTO")

# Create the table
ctable3 <- tibble(stations, approxDepth, nominalDepth, chl, nuts, sal, oxy, pco2, tic, poc, hplc, abs, cyto)

colnames(ctable3) <- header3

kbl(ctable3, 
    booktabs = TRUE,
    linesep = "",
    longtable = TRUE,
    format = "latex",
    escape = FALSE,
    align = "cccccccccccc",
    caption = "Summary of nominal depths of water sample collection and variables measured on the four AZMP fixed stations in the Gully MPA. Stations are organized from shallowest to deepest and include the approximate maximum depth based on station bathymetry extracted from GEBCO (2019). The ‘X’ and ‘XX’ indicate the nominal depth at which single (‘X’) and duplicate (‘XX’) samples are collected. ‘BTM’ indicates ‘near-bottom’. CHL = chlorophyll, NUTS = nutrients, SAL = salinity, O\\textsubscript{2} = dissolved oxygen, pCO\\textsubscript{2} = partial pressure of CO\\textsubscript{2}, TIC/TA = Total Inorganic Carbon and Total Alkalinity, POC = particulate organic carbon, HPLC = high performance liquid chromatography, ABS = phytoplankton absorption, and CYTO = flow cytometry for microbial plankton. \"$\\sim$\" represents approximately.") %>%
  kableExtra::collapse_rows(columns = 1:2, latex_hline = "major", valign = "middle") %>%
  # Make the header row bold text
  kableExtra::row_spec(0, bold = TRUE) %>%
  kableExtra::kable_styling(latex_options = "repeat_header", repeat_header_method = "replace")

```
\end{landscapepage}

\clearpage


\begin{landscapepage}

```{r table4, results="asis", include=TRUE, echo=FALSE}

years <- c(1999:2018)
years <- c(as.character(years), "No. of Tows:")
hl6s <- c("4,6","6","5","6","4","4,5","4","5","4","","4","4","4","","4","4,5","4","4","4","4,5","22")
sg28s <- c("","","","","","","","","","","4","","","","4","","4","","4","4","5")
guld4s <- c("","","","","","","","","4","","4","","","","4","","4","","4","4","6")
sg23s <- c("","","","","","","","","","","4","","","","","","4","","4","4","4")
guld3s <- c("","","","","","","","","4","","4","","","","","","4","4","4","4","6")
ll7s <- c("4","4","5","","4","4","4","4","4","4","4","4","4","","4","4","4","","4","4","17")
spring_tbl <- tibble(years,hl6s,sg28s,guld4s,sg23s,guld3s,ll7s, row.names = NULL)

hl6f <- c("11","10","10","10","10","10","10","10","10","10","10","11","9","9","9","9","10","9","11","9","20")
sg28f <- c("","","","","","","","","","10","","","","","9","9","","9","","9","5")
guld4f <- c("","","","","","","","","","","","","","","9","","9","","12","9","4")
sg23f <- c("","","","","","","","","","","","","","","9","9","9","9","12","9","6")
guld3f <- c("","","","","","","10","","10","10","","","","","9","9","9","9","12","9","9")
ll7f <- c("10","10","11","10","10","10","10","10","10","10","10","","10","","9","10","9","","12","9","17")
fall_tbl <- tibble(years,hl6f,sg28f,guld4f,sg23f,guld3f,ll7f, row.names = NULL)

ctable4 <- full_join(spring_tbl,fall_tbl)

header4 <- c("Year", "HL\\_06", "SG\\_28", "GULD\\_04", "SG\\_23", "GULD\\_03", "LL\\_07", "HL\\_06", "SG\\_28", "GULD\\_04", "SG\\_23", "GULD\\_03", "LL\\_07")

colnames(ctable4) <- header4

# csasdown::csas_table(ctable4,
#                      font_size = 11,
#                      format = "latex",
#                      align = rep("c", 13),
#                      caption = "Ring net samples collected at the four AZMP fixed stations in the Gully MPA and at core AZMP stations HL\\_06 and LL\\_07 in spring and fall between 1999 and 2018. The numbers represent the month of sample collection, where April-June represent spring and September-December represent fall. The total number of ring net tows collected at each station in each season is given below.") %>%
#   kableExtra::add_header_above(c(" " = 1, "Spring" = 6, "Fall" = 6), bold = TRUE, font_size = 12) %>%
#   kableExtra::row_spec(20, hline_after = TRUE) %>%
#   kableExtra::row_spec(21, bold = TRUE) %>%

kbl(ctable4, 
    booktabs = TRUE,
    linesep = "",
    format = "latex",
    escape = FALSE,
    align = "ccccccccccccc",
    caption = "Ring net samples collected at the four AZMP fixed stations in the Gully MPA and at core AZMP stations HL\\_06 and LL\\_07 in spring and fall between 1999 and 2018. The numbers represent the month of sample collection, where April-June represent spring and September-December represent fall. The total number of ring net tows collected at each station in each season is given below.") %>%
  # Make the header row bold text
  kableExtra::row_spec(0, bold = TRUE) %>%
  # Add a another header above the first.
  kableExtra::add_header_above(c(" " = 1, "Spring" = 6, "Fall" = 6), bold = TRUE, font_size = 11) %>%
  # Put a horizontal line afte the 20th row before the total row at the bottom of the table.
  kableExtra::row_spec(20, hline_after = TRUE) %>%
  # Bold the total row.
  kableExtra::row_spec(21, bold = TRUE) %>%
  # Alternate the rows with different colors to make it easier to read.
  kableExtra::kable_styling(latex_options = c("striped", "scale_down")) %>%
  # Add lines to the right of columns 1 and 5.
  kableExtra::column_spec (c(1,7), border_right = TRUE)

```
\end{landscapepage}

\clearpage


\begin{landscapepage}

```{r table5, results="asis", include=TRUE, echo=FALSE}

depths <- c("0 to 50", "50 to 100", "100 to 400", "400 to 750", "750 to near-bottom")
guld3s <- c("","0.550\\text{*}\\text{*}","0.806\\text{*}\\text{*}\\text{*}","0.611\\text{*}\\text{*}\\text{*}","")
sg28s <- c("0.598\\text{*}", "0.838\\text{*}\\text{*}", "0.790\\text{*}\\text{*}", "", "")
guld4s <- c("","0.694\\text{*}\\text{*}","0.835\\text{*}\\text{*}\\text{*}","0.532\\text{*}","")
sg23s <- c("","","0.638\\text{*}","","")
guld3f <- c("","","0.380\\text{*}","0.541\\text{*}\\text{*}","")
sg28f <- c("","","0.431\\text{*}","0.540\\text{*}","")
guld4f <- c("","","","0.641\\text{*}\\text{*}","")
sg23f <- c("","","0.533\\text{*}","","0.471\\text{*}")

ctable5 <- tibble(depths, guld3s, sg28s, guld4s, sg23s, guld3f, sg28f, guld4f, sg23f, row.names = NULL)

header5 <- c("Depth interval (m)", rep(c("GULD\\_03", "SG\\_28", "GULD\\_04", "SG\\_23"), 2))

colnames(ctable5) <- header5

kbl(ctable5, 
    booktabs = TRUE,
    linesep = "",
    format = "latex",
    escape = FALSE,
    align = c("c", rep("l", 8)),
    caption = "Pearson correlation coefficients (R\\textsuperscript{2}) and p-value significance resulting from linear regression models of the relationship between temperature and year measured at 5 depth intervals in spring and fall at each of the four AZMP fixed stations in the Gully MPA. Levels of significance are: * for p < 0.05, ** for p < 0.01 and *** for p < 0.001.") %>%
  # Make the header row bold text
  kableExtra::row_spec(0, bold = TRUE) %>%
  # Add a another header above the first.
  kableExtra::add_header_above(c(" " = 1, "Spring" = 4, "Fall" = 4), bold = TRUE, font_size = 12) %>%
  # Add lines to the right of columns 1 and 5.
  kableExtra::column_spec (c(1,5), border_right = TRUE)

```
\end{landscapepage}

\clearpage


\begin{landscapepage}

```{r table6, results="asis", include=TRUE, echo=FALSE}

areas <- c(rep("SW LL", 5), rep("GMPA", 5), rep("SW HL", 5))
metrics <- rep(c("Start", "Amplitude", "Duration", "Magnitude", "Jan to Apr SST"), 3)
amp <- c("","","","","","0.388\\text{*}\\text{*}","","","","","","","","","")
dur <- c("-0.560\\text{*}\\text{*}","","","","","-0.827\\text{*}\\text{*}","-0.492\\text{*}\\text{*}","","","","","","","","")
mag <- c("-0.295\\text{*}\\text{*}","","0.382\\text{*}\\text{*}","","","","","","","","","0.251\\text{*}","0.614\\text{*}\\text{*}","","")
sst <- c("","","","-0.330\\text{*}","","","","","","","0.339\\text{*}\\text{*}","","","-0.215\\text{*}","")
trd <- c("","","","","","","","","","0.251\\text{*}","","","","","0.344\\text{*}\\text{*}")

ctable6 <- tibble(areas, metrics, amp, dur, mag, sst, trd, row.names = NULL)

header6 <- c("Area", "Metrics", "Amp.", "Dur.", "Mag.", "Jan to Apr SST", "Trend")

colnames(ctable6) <- header6

kbl(ctable6, 
    booktabs = TRUE,
    linesep = "",
    format = "latex",
    escape = FALSE,
    align = c("c", rep("l", 5)),
    caption = "Pearson correlation coefficients (R\\textsuperscript{2}) between the four bloom metrics, between the metrics and winter-spring sea surface temperatures (Jan to Apr SSTs) and trends over the 1998 to 2018 period. Negative relationships are denoted by minus signs. Levels of significance are: * for p < 0.05, ** for p < 0.01 and *** for p < 0.001.") %>%
  # Make the header row bold text
  kableExtra::row_spec(0, bold = TRUE) %>%
  # Make the first column bold text and specify the column widths
  kableExtra::column_spec(1, bold = TRUE, width = "6em") %>%
  kableExtra::column_spec(2, width = "8em") %>%
  kableExtra::column_spec(3, width = "6em") %>%
  kableExtra::column_spec(4, width = "6em") %>%
  kableExtra::column_spec(5, width = "6em") %>%
  kableExtra::column_spec(6, width = "8em") %>%
  kableExtra::column_spec(7, width = "6em") %>%
  # Make the table text size 12 font.
  kableExtra::kable_styling(font_size = 12) %>%
  # Collapse the values in column 1 so values are not repeated.
  kableExtra::collapse_rows(columns = 1, latex_hline = "major", valign = "middle")

```
\end{landscapepage}

\clearpage


```{r table7, results="asis", include=TRUE, echo=FALSE}

zoopl <- c("LL\\_07/April", "Year", "\\textit{Microcalanus}", "\\textit{O. similis}", "\\textit{Pseudocalanus}", "\\textit{Scolecithrocella}", "GULD\\_03/April", "Year", "\\textit{C. hyperboreus}", "\\textit{M. lucens}", "HL\\_06/April", "Year", "\\textit{Clausocalanus}", "\\textit{Pleuromamma}", "\\textit{Pseudocalanus}")
fmt <- c("","0.37\\text{*}","","","","","","","","0.75\\text{*}","","","0.34\\text{*}", "0.50\\text{*}\\text{*}", "")
zmt <- c("","0.48\\text{*}\\text{*}","-0.27\\text{*}","","","-0.43\\text{*}\\text{*}","","0.72\\text{*}","-0.76\\text{*}","","", "", "0.48\\text{*}\\text{*}", "0.69\\text{*}\\text{*}\\text{*}", "-0.34\\text{*}")
yy <- c("", "", "", "-0.51\\text{*}\\text{*}", "-0.47\\text{*}\\text{*}", "-0.32\\text{*}", "", "", "-0.75\\text{*}", "", "", "", "", "", "")

ctable7 <- tibble(zoopl, fmt, zmt, yy, row.names = NULL)

header7 <- c("", "5 m T", "0 to 200 m T", "Year")

colnames(ctable7) <- header7

bold_cell <- c(T, rep(F, 5), T, rep(F, 3), T, rep(F, 4))

kbl(ctable7, 
    booktabs = TRUE,
    linesep = "\\addlinespace",
    format = "latex",
    escape = FALSE,
    align = rep("l", 4),
    caption = "Pearson correlation coefficients (R\\textsuperscript{2}) between zooplankton abundances and near surface temperatures and trends in both over time at HL\\_06, GULD\\_03 and LL\\_07 in spring (April) between 1999 and 2018. Negative relationships are denoted by minus signs. Levels of significance are: * for p < 0.05, ** for p < 0.01 and *** for p < 0.001.") %>%
  # Make the header row bold text
  kableExtra::row_spec(0, bold = TRUE) %>%
  # Make the text bold in three cells in column 1 and specify the column widths.
  kableExtra::column_spec(1, bold = bold_cell, width = "11em") %>%
  kableExtra::column_spec(2, width = "6em") %>%
  kableExtra::column_spec(3, width = "6em") %>%
  kableExtra::column_spec(4, width = "6em") %>%
  # Put horizontal lines after the 6th and 11th  rows to separate areas for easier reading.
  kableExtra::row_spec(c(6,10), hline_after = TRUE) %>%
  # Make the table's font size 12.
  kableExtra::kable_styling(font_size = 12, latex_options = "striped")

```
\clearpage


```{r table8, results="asis", include=TRUE, echo=FALSE}

zoopl <- c("LL\\_07/Fall", "Year", "\\textit{C. finmarchicus}", "\\textit{Clausocalanus}", "\\textit{Microcalanus}", "GULD\\_03/Fall", "Year", "\\textit{Clausocalanus}", "\\textit{M. lucens}", "HL\\_06/Fall", "Year", "\\textit{C. finmarchicus}", "\\textit{M. clausi}", "\\textit{M. lucens}", "\\textit{O. atlantica}", "\\textit{O. similis}", "\\textit{Paracalanus}", "\\textit{Pleuromamma}")
fmt <- c("","","-0.43\\text{*}\\text{*}","0.38\\text{*}","-0.31\\text{*}","","","","","","","-0.21\\text{*}","","","","","","")
zmt <- c("","","","0.62\\text{*}\\text{*}","","","","","","","","","","-0.34\\text{*}\\text{*}","-0.27\\text{*}","-0.47\\text{*}\\text{*}","-0.30\\text{*}","0.21\\text{*}")
yy <- c("","","","","-0.28\\text{*}","","","0.45\\text{*}","0.51\\text{*}","","","","-0.25\\text{*}","","","","","")

ctable8 <- tibble(zoopl, fmt, zmt, yy, row.names = NULL)

header8 <- c("", "5 m T", "0 to 200 m T", "Year")

colnames(ctable8) <- header8

bold_cell <- c(T, rep(F, 4), T, rep(F, 3), T, rep(F, 8))

kbl(ctable8, 
    booktabs = TRUE,
    linesep = "\\addlinespace",
    format = "latex",
    escape = FALSE,
    align = rep("l", 4),
    caption = "Pearson correlation coefficients (R\\textsuperscript{2}) between zooplankton abundances and near surface temperatures and trends in both over time at HL\\_06, GULD\\_03 and LL\\_07 in fall (Sept to Dec) between 1999 and 2018. Negative relationships are denoted by minus signs. Levels of significance are: * for p < 0.05, ** for p < 0.01 and *** for p < 0.001.") %>%
  # Make the header row bold text
  kableExtra::row_spec(0, bold = TRUE) %>%
  # Make the text bold in three cells in column 1 and specify the column widths.
  kableExtra::column_spec(1, bold = bold_cell, width = "11em") %>%
  kableExtra::column_spec(2, width = "6em") %>%
  kableExtra::column_spec(3, width = "6em") %>%
  kableExtra::column_spec(4, width = "6em") %>%
  # Put horizontal lines after the 5th and 9th  rows to separate areas for easier reading.
  kableExtra::row_spec(c(5,9), hline_after = TRUE) %>%
  # Make the table's font size 12.
  kableExtra::kable_styling(font_size = 12, latex_options = "striped")

```
\clearpage

