---
title: "Oceanographic monitoring of the Gully MPA – A synopsis of data collected by the Atlantic Zone Monitoring Program"
year: 2021
report_number: nnn
author: |
  Jeffrey W. Jackson^1^,
  Erica J. H. Head^1^,
  Lindsay I. Beazley^1^, and
  Andrew T. Cogswell^1^
author_list: "Jackson, J.W., Head, E.J.H., Beazley, L.I. and Cogswell, A.T."
region: Maritimes Region
isbn: ""
address: |
  ^1^Ocean and Ecosystem Sciences Division\
     Fisheries and Oceans Canada\
     Bedford Institute of Oceanography\
     P.O. Box 1006\
     Dartmouth, Nova Scotia\
     Canada, B2Y 4A2
phone: "(902) 426-2373"
author_footnote: "Email: Jeffrey.Jackson @ dfo-mpo.gc.ca"
abstract: |
  In 2004, the Gully was established as Atlantic Canada’s first Marine Protected Area (MPA) under Canada’s Oceans Act, with the goal of protecting its high biodiversity of cold-water corals and habitat for an endangered population of northern bottlenose whales. While the oceanographic setting of the Gully MPA has been described, little has been done to assess changes in its physical, chemical, or biological properties, a key component of evaluating whether the MPA is meeting its conservation objectives. Since the late 1990’s, the Atlantic Zone Monitoring Program (AZMP) has routinely collected hydrographic and biological data within the Gully MPA as part of the program’s ancillary objectives. However, these data had yet to be compiled and analyzed for the purpose of long-term environmental monitoring. Through a joint initiative between Fisheries and Oceans Canada’s Maritimes Region Canadian Science Advisory Secretariat and the AZMP, we present a compilation and reproducible analysis of the physical, chemical, and biological oceanographic data collected at four fixed sampling stations in the Gully between 2000 and 2018. Average temperature, salinity, dissolved oxygen, and nutrient and chlorophyll _a_ collected from CTD profiles and bottle samples were evaluated both within and among stations. Patterns of wet weight biomass and abundance of the most common copepod taxa from zooplankton samples collected from vertical ring net tows were also evaluated. Additionally, differences in sea surface temperature and chlorophyll _a_ from satellite-based imagery collected between 1998 to 2018 were examined in order to ascertain whether the surface properties of the MPA are unique relative to adjacent shelf-break areas. The main goal of this report is to provide operational advice for effective monitoring of the Gully’s oceanographic properties by the AZMP, with a focus on identifying redundancies and/or gaps in the program’s existing monitoring strategy for the MPA. We also provide a preliminary assessment of oceanographic environmental monitoring indicators presented in @kenchington_2010.
abstract_other: |
  En 2004, le Gully est devenu la toute première zone de protection marine (ZPM) désignée dans la région de l’Atlantique en vertu de la Loi sur les océans, dans le but de protéger sa grande biodiversité de coraux d’eau froide et l’habitat d’une population de baleines à bec communes en voie de disparition. Bien que le milieu océanographique de la ZPM du Gully ait été décrit, peu de choses ont été faites pour évaluer les changements dans ses propriétés physiques, chimiques ou biologiques, un élément clé pour déterminer si la ZPM atteint ses objectifs de conservation. Depuis la fin des années 1990, le Programme de monitorage de la zone Atlantique (PMZA) recueille régulièrement des données hydrographiques et biologiques dans la ZPM du Gully dans le cadre des objectifs auxiliaires du programme. Ces données n’avaient cependant pas encore été compilées et analysées en vue d’une surveillance environnementale à long terme. Grâce à une initiative conjointe entre le Secrétariat canadien de consultation scientifique de la région des Maritimes de Pêches et Océans Canada et le PMZA, nous présentons une compilation et une analyse reproductible des données océanographiques physiques, chimiques et biologiques recueillies à quatre stations d’échantillonnage fixes dans le Gully entre 2000 et 2018. Les données sur la température moyenne, la salinité, l’oxygène dissous, les nutriments et la chlorophylle _a_ qui ont été recueillies au moyen des profils de CTP et des bouteilles d’échantillonnage ont été évaluées à l’intérieur des stations et entre elles. On a également évalué les modèles de poids humide de la biomasse et de l’abondance des taxons de copépodes les plus communs observés dans les échantillons de zooplancton prélevés au moyen de filets à anneaux verticaux. De plus, les différences de température de la surface de la mer et de chlorophylle _a_ observées sur les images satellites recueillies entre 1998 et 2018 ont été examinées afin de déterminer si les propriétés de la surface de la ZPM sont uniques comparativement aux zones adjacentes du rebord du plateau continental. Le principal objectif de ce rapport est de fournir des conseils opérationnels pour assurer une surveillance efficace des propriétés océanographiques du Gully par le PMZA, en mettant l’accent sur le recensement des redondances et des lacunes dans la stratégie de surveillance existante du programme pour la ZPM. Nous offrons également une évaluation préliminaire des indicateurs de surveillance de l’environnement océanographique présentés dans @kenchington_2010.
output:
 csasdown::techreport_pdf:
   french: false
   copy_sty: false
   line_nums: false
   line_nums_mod: 1
   lot_lof: true
   latex_engine: xelatex
type:
  techreport
# ------------
# End of options to set
knit: bookdown::render_book
site: bookdown::bookdown_site
link-citations: true
bibliography: bib/refs.bib
lot: true
lof: true
# Any extra LaTeX code for the header:
header-includes:
 - \usepackage{float} \usepackage{xfrac} \usepackage{gensymb} \usepackage{multirow} \usepackage{colortbl} \usepackage{xcolor} \usepackage{bookmark} \usepackage{mathptmx} 

---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "png"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "png"
}
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "htb"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  #  autodep = TRUE,
  #  cache = TRUE,
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos
)
options(xtable.comment = FALSE)
options(kableExtra.latex.load_packages = FALSE)
```

```{r load-libraries, cache=FALSE}
# `french` and `prepub` variables are extracted from the YAML headers above and
#  are used throughout the document. To make the document all in french, change
#  the line in the YAML header above to `french: true`
meta <- rmarkdown::metadata$output
if(length(grep("pdf", names(meta)))){
  french <- meta$`csasdown::techreport_pdf`$french
  prepub <- meta$`csasdown::techreport_pdf`$prepub
}else if(length(grep("word", names(meta)))){
  french <- meta$`csasdown::techreport_word`$french
  prepub <- meta$`csasdown::techreport_word`$prepub
}
csl <- "csl/csas.csl"
if(french){
  csl <- "csl/csas-french.csl"
  options(OutDec =  ",")
}

# add other packages here:
library(plyr)
library(dplyr)
library(ggplot2)
library(readr)
library(rosettafish)
library(tibble)
library(remotes)
library(csasdown)
library(kableExtra)
library(lubridate)
library(readxl)
library(tidyr)
library(scales)
library(stringi)
library(stringr)
library(oce)
library(fs)
library(tidyverse)
library(cowplot)
library(egg)
library(ggpubr)
library(pracma)
library(ggthemes)

```

---
csl: `r csl`    
---
